### ISSUE TITLE
Last backslash before a heading/table gets preserved

### ISSUE THREAD

**Issue by DKhalil** [thephpleague/commonmark#1000]
### Version(s) affected

2.4.1

### Description

A forced line break with a backslash works as long as there's no heading or table element following it.

### How to reproduce

```markdown
# Hello
\
\
## Hello again
```

**Comment by colinodell** [comment]
That behavior is intentional.  According to the CommonMark spec:

> Hard line breaks are for separating inline content within a block. Neither syntax for hard line breaks works at the end of a paragraph or other block element

See https://spec.commonmark.org/0.29/#hard-line-breaks, as well as https://babelmark.github.io/?text=%23+Hello%0A%5C%0A%5C%0A%23%23+Hello+again showing how all CommonMark-compliant parsers behave this way.
