### ISSUE TITLE
Abbreviated decade (e.g. ’80s) breaks smart punctuation

### ISSUE THREAD

**Issue by barrymieny** [thephpleague/commonmark#1030]
### Version(s) affected

2.4.2

### Description

When the `QuoteParser` encounters a string such as:

```
In the middle to late ’90s, it was chaos. "We couldn't get out of that rut."
```

... it seemingly includes the apostrophe before 90 in its calculations, and you end up with a string like:

```
In the middle to late ‘90s, it was chaos. “We couldn’t get out of that rut.“
```

... where it replaces the already formatted closing single quote before 90 (which is how abbreviated decades should be formatted) with an opening single quote, and then the final double quote ends up as another opening double quote instead of a closing double quote.

I don't know whether the solution lies in the `QuoteParser` being aware of the abbreviated decade format or having the option to instruct it to disregard already formatted quotes or specify it to only format unformatted quotes.

I'm migrating a Node-based site that uses `markdown-it` to PHP, and `markdown-it` handles this situation properly, so there does seem to be a way to interpret this.

### How to reproduce

I tested this with the `GrahamCampbell/Laravel-Markdown` package as well as using `thephpleague/commonmark` directly, so the problem does seem to lie within this package in either the `QuoteParser` or `QuoteProcessor`.

To reproduce, use any decade abbreviation (e.g. `'60s` unstyled or `’70s` styled) in a paragraph with other quoted text. Both will result in the wrong formatting.

**Comment by colinodell** [comment]
Thanks for the highly detailed bug report!

The [smart punctuation spec](https://github.com/commonmark/commonmark.js/blob/master/test/smart_punct.txt) doesn't dictate how already-formatted quotes should be handled.  It seems that I must have decided at some point that we should try to correct bad formatting, like `”backwards quotes“`, and I implemented this by normalizing all quotes (including the already-formatted ones) into `"` or `'` and _then_ applying the algorithm.

In retrospect, I think this was the wrong approach, for three reasons:

1. We should respect existing formatting choices (as you suggest)
2. The spec doesn't call for this extra normalization
3. The `commonmark.js` library which introduced that spec doesn't apply that extra normalization

So I think the correct change would be to ignore any already-formatted quotes.  I'll put together a PR for this.
