### ISSUE TITLE
Problems with QuoteParser.php file permissions

### ISSUE THREAD

**Issue by VelziDM** [thephpleague/commonmark#1042]
### Version(s) affected

2.4.4 and all after

### Description

**Issue Title:** Permission Issues with Composer Package Installation on 
macOS Sonoma(Version 14.5)

**Description:**

After updating to the latest version of CommonMark (commit 
`50bd4dce0d53e1b3b51a153fc2e44a7dc3f7ee5b`), [file before commit](https://github.com/user-attachments/assets/cf558dd0-b900-4747-b8cd-3f3b216ad618) 
I'm experiencing permission 
issues with Composer package installation on macOS.

**Issue Summary:**

When installing a Composer package, my colleagues and I are encountering 
an issue where the file is created empty and cannot be modified, even when 
using `sudo`. This prevents Composer from creating the autoloader file.

### How to reproduce

Scenario 1.
1. Install the version of CommonMark after 2.4.3.
2. Attempt to install a Composer package using the usual command 
(`composer install` or `composer update`).
3. Observe that the file is created empty and cannot be modified, even 
when using `sudo`.
[screenshot 1](https://github.com/user-attachments/assets/52d095bd-f15f-401c-bd98-75a57d7e2285)
[screenshot 2](https://github.com/user-attachments/assets/0ca2aeac-d3c1-4c5f-831b-9a050fd2813a)

Scenario 2.
1. Download source code from github version after 2.4.3.
2. Observe that the file is empty and cannot be modified, even 
when using `sudo`.
[screenshot 1](https://github.com/user-attachments/assets/879b698e-cf27-49a3-9c3f-31d6c467a095)
[screenshot 2](https://github.com/user-attachments/assets/2f2eea1f-ae5e-4eab-8870-93798c07a643)

**Expected Behavior:**

The Composer package should be installed successfully, creating the 
required files with proper permissions.

**Actual Behavior:**

The file is created empty and cannot be modified, preventing Composer from 
creating the autoloader file.

### Possible solution

Downgrade to "league/commonmark": "2.4.3", helps.

### Additional context

Not reproduced on windows

### Did this project help you today? Did it make you happy in any way?

Someday we will be cool as you are)

**Comment by colinodell** [comment]
Hey there!

> where the file is created empty and cannot be modified
>
> This prevents Composer from creating the autoloader file.

Composer is responsible for writing those files.  It sounds like you might be experiencing issues related to your local filesystem.  Unfortunately we don't provide help for Composer or macOS filesystem problems (since they're beyond the scope of this project), but I'd recommend trying to delete your entire `vendor` directory and re-running `composer install`.  If that fails, double-check your file permissions and ownership on your project directory, or seek help from any other knowledgeable macOS users.

I hope you're able to figure this out!
