### ISSUE TITLE
Math extension

### ISSUE THREAD

**Issue by cavid90** [thephpleague/commonmark#1053]
### Description

I would like to have a Math extension which converts math formulas. At the moment it does not do it

### Example

At the moment it returns text as like this:
[ \text{Expression: } 10 \times 2 - 55 + 99 ]

Perform the multiplication: [ 10 \times 2 = 20 ]

Substitute the result of the multiplication back into the expression: [ 20 - 55 + 99 ]

Perform the subtraction: [ 20 - 55 = -35 ]

Perform the addition: [ -35 + 99 = 64 ]

So, ( 10 \times 2 - 55 + 99 = 64 ).

Where \times should be x or *

**Comment by colinodell** [comment]
Thanks for the idea! 

Unfortunately, due to limited time and funding, this is probably not something we'll be implementing in this repository. But if you or somebody else would like to create your own extension time be happy to promote it in our README!
