### ISSUE TITLE
2.6 security docs are missing max_delimiters_per_line

### ISSUE THREAD

**Issue by Pyker** [thephpleague/commonmark#1058]
### Version(s) affected

2.6

### Description

The [security doc page for 2.6](https://commonmark.thephpleague.com/2.6/security/) is missing `max_delimiters_per_line`, which is present in [the 2.5 security doc page](https://commonmark.thephpleague.com/2.5/security/).

### How to reproduce

Check https://commonmark.thephpleague.com/2.6/security/, see that `max_delimiters_per_line` is missing from there, and that it's present in https://commonmark.thephpleague.com/2.5/security/.

**Comment by Pyker** [comment]
Looking at this again, I just realized that `max_delimiters_per_line` isn't even supposed to be in the 2.5 page, because it was introduced in 2.6.

**Comment by Pyker** [comment]
I think https://github.com/thephpleague/commonmark/commit/51567969678a3b83ecdd83e3b1c834b577fd79a2 possibly inadvertently modified the 2.5 docs.

**Comment by Pyker** [comment]
Additionally, the lines at https://github.com/thephpleague/commonmark/blob/6294d44b09add8a894f30bfe7271444a0598e1bf/docs/_data/menu.yml#L6 and https://github.com/thephpleague/commonmark/blob/6294d44b09add8a894f30bfe7271444a0598e1bf/docs/_data/menu.yml#L53 should be updated to reflect "Upgrading from 2.4"/"Upgrading from 2.5".

**Comment by colinodell** [comment]
Oops! 😅  Both have been fixed via 88365ec0.  Thank you so much for catching and reporting this!
