### ISSUE TITLE
Extra spaces present in li tags with links

### ISSUE THREAD

**Issue by efc** [thephpleague/commonmark#1059]
### Version(s) affected

2.6

### Description

When I create a list...

```markdown
- one
- two [link](url)
- [link](url) three
- [four link](url)
```

What is rendered is this...

```html
<ul>
<li>one</li>
<li>two <a href="url">link</a>
</li>
<li>
<a href="url">link</a> three</li>
<li>
<a href="url">four link</a>
</li>
</ul>
```

Each one of the `<li>` tags is rendered with different spacing. The first has no spaces around the given content. The second has a space at the end, produced by the newline after the `</a>`. The third has a space at the beginning produced by the newline before the `<a>`. The fourth has newlines before and after the list item content.

It seems that a newline is being placed before or after the link depending on whether it is at the start or end (or both) of the list item.

This inconsistency makes using CSS `li::before` or `li::after` content on list items unpredictable. And it makes it completely impossible to create, for example, some `li::after` text that should never be separated from the list item by any space at all.

It seems wrong for extra spaces to be introduced into these list items. The consistent and correct rendering would be something like this.

```html
<ul>
<li>one</li>
<li>two <a href="url">link</a></li>
<li><a href="url">link</a> three</li>
<li><a href="url">four link</a></li>
</ul>
```

Is it possible to achieve that?

### How to reproduce

```markdown
- one
- two [link](url)
- [link](url) three
- [four link](url)
```
I am using Laravel and Statamic, which seem to use 2.2.1 by default (which exhibits the same behavior). I have updated my version to 2.6 to confirm the problem still exists.

[composer.lock.txt](https://github.com/user-attachments/files/18175221/composer.lock.txt)

**Comment by samwilson** [comment]
[Looks like](https://spec.commonmark.org/dingus/?text=-%20one%0A-%20two%20%5Blink%5D(url)%0A-%20%5Blink%5D(url)%20three%0A-%20%5Bfour%20link%5D(url)%0A-%20five%20%5Blink%5D(url)%20text%0A) commonmark.js is more consistent.

**Comment by colinodell** [comment]
Thanks for reporting this bug and providing so much detail around it!

> It seems that a newline is being placed before or after the link depending on whether it is at the start or end (or both) of the list item.

Yeah, we're using a *very* naive approach to determine whether to add newlines:

https://github.com/thephpleague/commonmark/blob/d150f911e0079e90ae3c106734c93137c184f932/src/Extension/CommonMark/Renderer/Block/ListItemRenderer.php#L41-L48

Basically, we're adding newlines around **any** HTML elements, whereas libraries like commonmark.js and commonmark-java only add them around **block-level** elements.  (They also use a completely different rendering system that makes this easier.)

I have an idea on how we can easily fix this.  Let me put a PR together.

**Comment by colinodell** [comment]
Fix has been released! https://github.com/thephpleague/commonmark/releases/tag/2.6.1
