### ISSUE TITLE
List of external extensions, parsers, and renderers

### ISSUE THREAD

**Issue by ErichHartmann** [thephpleague/commonmark#128]
Encourage community created extensions, parsers, and renderers that are written for thephpleague/commonmark to identify themselves here in the readme or via the docs.

The webuni/commonmark-table-extension is a good example of one of the view plugins that are readily identifiable.

**Comment by colinodell** [comment]
I've added readme sections for both [integrations](https://github.com/thephpleague/commonmark/blob/master/README.md#integrations) and [3rd-party extensions](https://github.com/thephpleague/commonmark/blob/master/README.md#community-extensions).  Anyone is welcome to submit a PR to add theirs to the list :)
