### ISSUE TITLE
Automate code style checks

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#133]
Perhaps use https://styleci.io/ as suggested by @GrahamCampbell [here](https://github.com/thephpleague/commonmark/pull/132#issuecomment-118845310)?

**Comment by GrahamCampbell** [comment]
We support configuration too, so if you don't like our default checks, you can tell us to just use PSR-2 and nothing extra.

**Comment by colinodell** [comment]
@GrahamCampbell How do I disable the end-every-comment-with-a-period rule?  (Is there a list of configuration settings readily available somewhere?)

**Comment by GrahamCampbell** [comment]
> end-every-comment-with-a-period rule

Disable `phpdoc_short_description`. :)

**Comment by GrahamCampbell** [comment]
The current version of StyleCI uses 1.9.1 of https://github.com/FriendsOfPHP/PHP-CS-Fixer.

Soon we're moving to 2.0-dev though. We'll notify all our users 5 days before we upgrade.

**Comment by GrahamCampbell** [comment]
I'd recommend you don't disable the rule though since short descriptions are meant to be actual sentences, so are required to start with a capital letter and end with a full stop.

**Comment by colinodell** [comment]
I really like the ruleset you suggested.  Thanks so much for helping with this!

**Comment by GrahamCampbell** [comment]
No problem. :)
