### ISSUE TITLE
Markdown renderer

### ISSUE THREAD

**Issue by fesor** [thephpleague/commonmark#141]
Is it possible to dump AST of document back into markdown? As I can see implementing of `MarkdownRenderer` is not possible since renderers depends on `HtmlRendererInterface` and every renderer should implement it.

I working on api-blueprint parser and i wish to dump some parts of a markdown AST into standalone markdown strings.

**Comment by cebe** [comment]
desite the name which includes the term Html it should be possible to turn the AST back into markdown with it, just do not create Html entities but the markdown string you need...

btw, @colinodell is there a reason why this interface includes Html in its name?

**Comment by colinodell** [comment]
> btw, @colinodell is there a reason why this interface includes Html in its name?

Nope, I'm just really bad at naming things.  You're right, the interface should be more generic.  I'll work on that sometime soon.

**Comment by cebe** [comment]
:+1:
