### ISSUE TITLE
Image class attribute

### ISSUE THREAD

**Issue by jbrooksuk** [thephpleague/commonmark#145]
It should be possible to add a class to an image.

**Comment by colinodell** [comment]
The CommonMark spec does not currently support this, and therefore our parser doesn't either.  However, this [CommonMark Attributes Extension](https://github.com/webuni/commonmark-attributes-extension) might add the functionality you're looking for - I'd recommend giving that a try.

**Comment by jbrooksuk** [comment]
@colinodell sorry, I didn't really explain my issue very well.

I'm not after a way to set the class name from within the Markdown source, but instead I need a way to set the class from the code itself.

The reason is for this; https://github.com/AltThree/Emoji/issues/2

**Comment by colinodell** [comment]
Ah okay, I understand now, sorry about that.

The ability to set HTML attributes, especially classes, is something that has come up before (#32, #33, #101).  Although I'm usually against adding functionality not strictly related to parsing CommonMark, I am warming up to this idea.

What do you think about #101 in particular?  Would something like that suit your needs?

**Comment by hason** [comment]
@jbrooksuk You can use [HtmlRender](https://github.com/webuni/commonmark-attributes-extension/blob/master/src/HtmlRenderer.php) from [CommonMark Attributes Extension](https://github.com/webuni/commonmark-attributes-extension):

```php
use League\CommonMark\DocParser;
use League\CommonMark\Environment;
use Webuni\CommonMark\AttributesExtension\HtmlRenderer;

$environment = Environment::createCommonMarkEnvironment();

$parser = new DocParser($environment);
$ast = $parser->parse('...');

// programatically set $ast->...imageBlock->data['attributes']['class'] = 'my-class';

$renderer = new HtmlRenderer($environment));
echo $renderer->renderBlock($ast);
```

**Comment by GrahamCampbell** [comment]
Using a custom html renderer isn't really ideal for us. It would be better for everyone if commonmark supported this stuff.

**Comment by colinodell** [comment]
I totally agree with @GrahamCampbell - that's a major reason I'm reconsidering this.

**Comment by GrahamCampbell** [comment]
:)

**Comment by jbrooksuk** [comment]
@colinodell I'll take a proper look at #101 tomorrow :)

**Comment by jbrooksuk** [comment]
@colinodell looks good. Any chance we can move forward? :)

**Comment by colinodell** [comment]
Yep I'll work on getting that implemented this weekend.

**Comment by GrahamCampbell** [comment]
:+1: :beers:

**Comment by jbrooksuk** [comment]
@colinodell thanks, that's awesome!

**Comment by colinodell** [comment]
This has been implemented :)

**Comment by jbrooksuk** [comment]
Amazing, thank you @colinodell
