### ISSUE TITLE
Possible discrepancy

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#168]
Run this through Babelmark2:

~~~markdown
- ### Header

  Description
~~~

(or, if you're lazy, [click here](http://johnmacfarlane.net/babelmark2/?normalize=1&text=-+%23%23%23+Header%0A%0A++Description))

commonmark 0.21 wraps `Description` in paragraph tags whereas version 0.10 of our library does not.  commonmark.js [also behaves similarly](http://spec.commonmark.org/dingus/?text=-%20%23%23%23%20Header%0A%0A%20%20Description).  So this might be a bug with our library.

**Comment by kkiernan** [comment]
What is the reason for the ```inTightList``` check in [ParagraphRenderer.php](https://github.com/thephpleague/commonmark/blob/master/src/Block/Renderer/ParagraphRenderer.php)? Keeping only the else block seems to create the desired result I think, but I'm unsure other effects this would have.

**Comment by colinodell** [comment]
`inTightList` has the wrong value, which seems to be caused by `lastLineBlank` not being set correctly somewhere.  I'll keep digging around and see what I can find.

**Comment by colinodell** [comment]
There were a couple issues with how I implemented the `lastLineBlank` functionality which ultimately caused this issue [as well as this](https://github.com/thephpleague/commonmark/pull/174#issuecomment-136070386).  It has been corrected by commit https://github.com/thephpleague/commonmark/commit/150679469530890f9b50f4f27835f156a9360fb5, which is part of pull request #174.
