### ISSUE TITLE
Accents not rendered properly

### ISSUE THREAD

**Issue by BadChoice** [thephpleague/commonmark#170]
I found that accents áéíóúàèìòù are not rendered correctly

**Comment by colinodell** [comment]
Would you mind providing an example of this behavior?  Perhaps a screenshot of the Markdown and resulting HTML?  I'm unable to replicate this issue locally or via Babelmark2: http://johnmacfarlane.net/babelmark2/?normalize=1&text=%C3%A1%C3%A9%C3%AD%C3%B3%C3%BA%C3%A0%C3%A8%C3%AC%C3%B2%C3%B9

**Comment by BadChoice** [comment]
Sorry, just fund that adding ```<meta charset="UTF-8">``` solved it..
