### ISSUE TITLE
How to prevent unwanted HTML from breaking parent layout 

### ISSUE THREAD

**Issue by emersonthis** [thephpleague/commonmark#175]
I'm using commonmark to parse markdown from GitHub issue comments that I'm fetching via their api. I notice in some situations the HTML in the comment gets rendered and breaks the parent layout.

[This issue](https://github.com/jquery/jquery-mobile/issues/7406) is a good example of my problem. It has a an entire an entire HTML document which causes weird things to happen when parsed.

Is this something I should address with an `addBlockParser()`? Or is this outside the scope of what this library does?

**Comment by colinodell** [comment]
Well, I think the HTML generated by this library should be valid (unless you're using invalid raw HTML, which isn't the case here).

I tried a quick test myself using that specific issue you referenced and wasn't able to replicate that behavior - it properly wrapped the entire code sample in `<pre><code>` as expected:

![image](https://cloud.githubusercontent.com/assets/202034/9618322/a0df3a1c-50d3-11e5-9f21-0fdadd1f2689.png)

![image](https://cloud.githubusercontent.com/assets/202034/9618334/b6b149b6-50d3-11e5-96cf-aa67ff5331b4.png)

If you could send along some kind of test or sample code that would be super helpful!

**Comment by colinodell** [comment]
Issue closed due to insufficient information.  Please feel free to re-open this if anything changes.
