### ISSUE TITLE
Add location to AST

### ISSUE THREAD

**Issue by cmkilger** [thephpleague/commonmark#176]
I'd like to get the location of each node of the tree relative to the original input text, either line/column or number of characters from the beginning. I was looking for a way to add it, but I don't quite understand the code that well yet, and it didn't seem straight forward to implement.

**Comment by cmkilger** [comment]
And I do see start and end lines for blocks, but I want it for each inline as well, e.g. text, emphasis, html, etc. I also saw that the start line wasn't set for some headers. Bug?

**Comment by colinodell** [comment]
> I do see start and end lines for blocks, but I want it for each inline as well, e.g. text, emphasis, html, etc.

Unfortunately source positions for inline elements aren't always useful: https://github.com/jgm/commonmark.js/issues/64#issuecomment-136869977

I'd like to monitor how the upstream projects handles this (possibly [using source maps](https://github.com/jgm/commonmark.js/issues/29) instead) and the implement the same approach for consistency.  I'm therefore going to close this issue (for now, at least).

See also:

 - https://github.com/jgm/commonmark.js/issues/28
 - https://github.com/jgm/CommonMark/issues/57

> I also saw that the start line wasn't set for some headers. Bug?

Quite possibly.  If you wouldn't mind opening a separate issue (with some examples of this bug) I'd greatly appreciate it!

Thanks!
