### ISSUE TITLE
CLI Rendering

### ISSUE THREAD

**Issue by AydinHassan** [thephpleague/commonmark#180]
Hey, sorry this is more a support/advice question.

I need to write a CLI output formatter for Markdown, and was wondering if you could give some insight on how I might do it with this library? Or even if it would suite it, from a quick glance it obviously seems to be centered around HTML.

* Would It be feasible to implement it as a custom renderer?
* Should I just take the AST and render it myself?

Any advice would be great :) Feel free to close this if there is a better means to get in contact!

**Comment by colinodell** [comment]
Either approach should work just fine - I'd go with whichever you think fits your methodology best.  If our rendering process isn't a great fit, then perhaps the AST-based approach would be better for you.

Just a heads-up that I'm hoping to release a new version this weekend with major changes to the AST.  The changes are already in `master` and the CHANGELOG, but not the documentation (yet), so feel free to take a look.

I'm going to close this issue, but I'd be happy to answer any other specific questions you might have!

**Comment by AydinHassan** [comment]
@colinodell Thanks for the advice, I had a go at it today and came up with this: https://github.com/AydinHassan/cli-md-renderer. I tried to follow the existing interfaces but they didn't fit as it was very much tied with HTML (for good reason).

Mine isn't very flexible at the minute, no configuration as such. Would be great if you could spare a second to look over at some point :D 

Thanks!
