### ISSUE TITLE
LogicException: You cannot add lines to a block which cannot accept them

### ISSUE THREAD

**Issue by anthonyryan1** [thephpleague/commonmark#183]
Noticed this when upgrading from 0.10.0 to 0.11.1.

# Exception trace

src/Block/Element/AbstractBlock.php in addLine at line 233

    throw new \LogicException('You cannot add lines to a block which cannot accept them');

src/Block/Element/IndentedCode.php in handleRemainingContents at line 94

    $context->getTip()->addLine($cursor->getRemainder());

src/DocParser.php in incorporateLine at line 133

    $context->getContainer()->handleRemainingContents($context, $cursor);

src/DocParser.php in parse at line 86

    $this->incorporateLine($context);

src/Converter.php in convertToHtml at line 59

    $documentAST = $this->docParser->parse($commonMark);

# Minimal test case

```
10. Bullet

        code


Test
```

**Comment by colinodell** [comment]
This appears to be an issue with the upstream implementation: https://github.com/jgm/commonmark.js/issues/67

I think I've got a possible solution, which I'll implement immediately to mitigate the issue.  Although this should eliminate the exception being thrown, it may result in some incorrect output in certain complex cases.  We'll make sure this library ultimately matches whatever solution is implemented upstream, ensuring that our output is correct.

**Comment by colinodell** [comment]
I've just released 0.11.2 which fixes the issue.  Should upstream choose a different fix, we'll implement that and release another update.
