### ISSUE TITLE
Investigate container vs tip

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#186]
Perhaps we only need one (not both) stored in the `Context`?

cmark operates without a tip, and commonmark.js seems to use containers locally.  This makes me wonder whether we truly need both a tip and a container tracked within the Context, instead of just one or the other.

**Comment by fesor** [comment]
I don't think that we need both container and tip.

**Comment by colinodell** [comment]
After reviewing cmark it appears that `tip` is definitely important and must be kept within that parent context.  `container` also needs to be made available to the parsers - in cmark it is passed directly into the parse methods, but we also leverage the context for that purpose.

I'm therefore okay keeping this as-is.
