### ISSUE TITLE
Blockquote issue 

### ISSUE THREAD

**Issue by ArabCoders** [thephpleague/commonmark#199]
Hi, 

I'm trying to switch from using `cebe\markdown` to this package, while i was checking few stuffs around, i've noticed that `league/commonmark` does not parsing the following example, Not sure if this is intended or not but i thought i may as well send in a report about it, it seems once you escape text using `htmlspecialchars()`, the blockquote parser stop working, while `cebe\markdown` still parse it correctly.

```php
<?php
require 'vendor/autoload.php';

use \League\CommonMark\CommonMarkConverter;

$cm = new CommonMarkConverter();

$text = 'this is test'.PHP_EOL;
$text .= '> test blockquote.'.PHP_EOL;
$text .= '> test blockquote2.'.PHP_EOL;
$text .= 'extra text';

$text = htmlspecialchars($text);

echo $cm->convertToHtml($text) . PHP_EOL;

**Comment by mAAdhaTTah** [comment]
That seems like a bug in `cebe\markdown`; if the `>` is an HTML entity, it shouldn't be parsed as Markdown.

**Comment by ArabCoders** [comment]
Hmm

Indeed looking at babelmark2 it seems i have older version of `cebe\markdown` or something else is converting it back to normal text instead of HTML entity.

**Comment by colinodell** [comment]
> if the > is an HTML entity, it shouldn't be parsed as Markdown.

Yep, good call @mAAdhaTTah!

I'm going to mark this as closed for now, but we can certainly reopen it if there's any issue on our end.  Thanks for submitting!
