### ISSUE TITLE
No method to escape Markdown user input without breaking block quotes

### ISSUE THREAD

**Issue by gytdau** [thephpleague/commonmark#200]
There's no satisfactory way to escape user-submitted Markdown as it uses the the angle bracket `>` for a block quote, which is escaped into `&gt;` by default.

Example:
```
# Title 1

<script src="example.com"></script>

> Blockquote
```

Escaped:

```
# Title 1

&lt;script src=&quot;example.com&quot;&gt;&lt;/script&gt;

&gt; Blockquote
```
The issue here is that the blockquote is no longer recognized as valid Markdown. One solution could be adding your own escape function that ignores all right-angle brackets that are the first character on a line, which would instead convert it to:
```
# Title 1

&lt;script src=&quot;example.com&quot;&gt;&lt;/script&gt;

> Blockquote
```
... which then would result in the expected Markdown, with the blockquote intact. Another solution would be to treat the characters `&gt;` as the right angle bracket itself.  

I'm not sure about the impact or complexity of these solutions, so feel free to just throw them out the window.

**Comment by GrahamCampbell** [comment]
NB, the spec is https://github.com/jgm/CommonMark, so, this issue probably belongs on commonmark itself, rather than this implementation of it.

**Comment by colinodell** [comment]
It might be possible if you tinker with adding/removing/adjusting the HTML
parsers/renderers. I'd like to simplify this though because it's a common
use case. Basically we'll add a simple config setting to toggle whether
HTML should be left as-is or be escaped.

I'm currently out-of-town and I'll be very busy over the next few weeks, so
it may not get done right away.

**Comment by GrahamCampbell** [comment]
Would still be nice if we could get this into the official spec in some way since it's surely a pretty common thing people want from markdown.

**Comment by colinodell** [comment]
Based on my research, the spec maintainers have decided that this doesn't belong in the spec:

- https://github.com/jgm/CommonMark/issues/61
- http://talk.commonmark.org/t/cross-site-scripting-issue-in-standard-markdown-example-at-try-standardmarkdown-com/55/6

The JS reference parser has implemented a `safe` configuration option which is basically what I'd like to replicate: https://github.com/jgm/commonmark.js/commit/57a1ae3ce97f4794f89658cd90b4e4f8d2c9d5a9

**Comment by colinodell** [comment]
@gytdau Please take a look at #201 and let me know what you think.

**Comment by gytdau** [comment]
@colinodell That looks great.:thumbsup:

**Comment by colinodell** [comment]
#201 has been merged. I'll try to tag a new release later today.
