### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by adam-boduch** [thephpleague/commonmark#204]
Hello

I've been thinking about using commonmark in my project. Problem is I need to write some extensions. First of all I need to replace all offensive words in text (like fuck => f***). Second of all I need to convert all links into <a>.

I've been trying to do it by my own but there is a lack of examples (I found only this: http://commonmark.thephpleague.com/customization/inline-parsing/). Can you provide some useful tips how to achieve this goal?

Thank you. I'd really appreciate it.

**Comment by colinodell** [comment]
I've created a new package [league/commonmark-extras](https://github.com/thephpleague/commonmark-extras).  The goal of this project is to provide real-world examples of custom functionality.  It's my hope that this will slowly grow over time.

Additionally, I do plan on updating the docs soon.  I'll try to add some more example while I'm making those updates.

**Comment by colinodell** [comment]
Docs have been updated with a couple more examples.
