### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by Arcesilas** [thephpleague/commonmark#228]
Hi,

This package is really great and the documentation is really good, even if not perfectly complete.

I've noticed two little errors and I don't really know where to mention them, since there is no wiki and no repo for the doc (so, opening a new issue).

http://commonmark.thephpleague.com/customization/inline-rendering/
Paragraph: Designating Inline Renderers
Wrong method is used: `addBlockRenderer` instead of `addInlineRenderer`

```php
$environment->addBlockRenderer('League\CommonMark\Inline\Element\Link', new MyCustomLinkRenderer());
```

And the last line of the example code does not use the correct class (Link is missing):
```php
$environment->addInlineRenderer('League\CommonMark\Inline\Element\', new MyCustomLinkRenderer());
```

Took me some minutes to find out why my renderer did not work.

**Comment by colinodell** [comment]
Thanks for catching that!

The docs live under [the `gh-pages` branch](https://github.com/thephpleague/commonmark/tree/gh-pages).  If you'd like to submit a PR to fix this I'd greatly appreciate it!  Otherwise I'll try to get to this sometime soon.

**Comment by Arcesilas** [comment]
Done :)
