### ISSUE TITLE
Bootstrap Support?

### ISSUE THREAD

**Issue by ScooterSam** [thephpleague/commonmark#256]
So basically. We use bootstrap, and we're using this to empower the forum.
Except, when a user posts an image, it won't contain the "img-responsive" class, is there any way i can do this without modifying the package, or could basic support be added?

It probably wouldn't be too easy to implement, I cannot image it would be. But I'm maybe thinking, you could add a Class config array to the initiation?

Then we could do something like 
[
'img' => [
'img-responsive
]
]

classname => [classes to add as default?]

I feel this could work well? I noticed you have the support added for it :p

**Comment by royduin** [comment]
Thanks for your example @colinodell, how I've implemented it with https://github.com/GrahamCampbell/Laravel-Markdown: https://github.com/GrahamCampbell/Laravel-Markdown/issues/58#issuecomment-324039047
