### ISSUE TITLE
How to allow nested element

### ISSUE THREAD

**Issue by yellow1912** [thephpleague/commonmark#263]
I'm implementing  a custom parser/render with a custom element, my custom element looks like this

```
[opentag]

something here

1. abc
2. xyz

__something important__

[closetag]
```

The problem is that in the renderer, when I getStringContent from the block I seem to miss all the contents such as the list or the emphasized text and only get the plain text?

Edit: seem like my particular issue is with rendering both inline and block elements inside my custom block.

**Comment by colinodell** [comment]
Your custom element should be implemented as a [container block](http://spec.commonmark.org/0.26/#container-blocks).  This means that your block will contain other blocks.

IIRC, `getStringContent()` is primarily for inline text content of a block, not the rendered content of child blocks.  So in your renderer, you'll need to manually render those children and wrap them with your custom element.  For example:

```php
$innerElements = $htmlRenderer->renderBlocks($block->children());
$separator = $htmlRenderer->getOption('inner_separator', "\n");

return new HtmlElement(
    'div',
    ['class' => 'my-custom-element'],
    $separator . $innerElements . $separator
);
```

(I have not tested the code above but it should work)

I'd recommend looking at how the BlockQuote element, parser, and renderer are implemented - that should give you a good guide.

**Comment by jtojnar** [comment]
I am also fighting with parsing nested containers:

https://stackoverflow.com/questions/41211251/how-to-parse-nested-containers-with-commonmark-for-php

**Comment by colinodell** [comment]
@jtojnar I left an answer on your SO post, please check that out and let me know if that helps.

**Comment by colinodell** [comment]
To answer the general question here, I think these points will help:

1. Make your parser check for both the opening and closing syntax.
2. The order in which block parsers are added is important.  Yours might need to run before others.
3. The context's container and tip are usually set automatically.  You can manually set them yourself during the block parsing if needed.
4. When debugging, it may help to trace through `DocParser::incorporateLine`, especially the calls to:
  - `resetTip()`
  - `resetContainer()`
  - `closeUnmatchedBlocks()`

**Comment by jtojnar** [comment]
@colinodell That certainly did help, although now many empty paragraphs are generated. Is it possible to fix it on parser-level, rather than by post-processing the document?

Updated code: https://gist.github.com/jtojnar/d866ca3bdb78b44267e5bf5563f04554
Another AST: https://gist.github.com/jtojnar/d571a1d6c249f27d8606daa5e5648bca
