### ISSUE TITLE
How to use HtmlInline?

### ISSUE THREAD

**Issue by josephxanderson** [thephpleague/commonmark#265]
Hi!

I'm trying to use HtmlInline to append to my html. However, it seems like there's no code in the actual HtmlInline.php file, which means nothing's being rendered I suppose. If I'm wrong, how can I use it? Otherwise, is it possible to get that fixed?

Thanks!

**Comment by colinodell** [comment]
This class extends from `AbstractStringContainer`, so you can add the HTML using the constructor or `setContent()` method:

```php
$html = new HtmlInline('<h1>Hello World!</h1>');
```

Or:

```php
$html = new HtmlInline();
$html->setContents('<h1>Hello World!</h1>');
```

The rendering is handled by the `HtmlInlineRenderer`: https://github.com/thephpleague/commonmark/blob/167531131ee516767e96f5af7ac6c430622bbaf5/src/Inline/Renderer/HtmlInlineRenderer.php#L56

You can find a couple examples of this in action:

 - https://github.com/thephpleague/commonmark/blob/167531131ee516767e96f5af7ac6c430622bbaf5/tests/unit/Inline/Renderer/HtmlInlineRendererTest.php#L38
 - https://github.com/thephpleague/commonmark/blob/34c45b6a0829da51410ecd0587b6723394f0b285/src/Inline/Parser/HtmlInlineParser.php#L40

**Comment by joexanderson** [comment]
@colinodell Thanks for your response. I appreciate it!

I have tried your suggestions:
```
    public function getCharacters()
    {
        return [':'];
    }

    /**
     * Parse a line and determine if it contains an emoji.
     *
     * If it does, then we do the necessary.
     *
     * @param \League\CommonMark\InlineParserContext $inlineContext
     *
     * @return bool
     */
    public function parse(InlineParserContext $inlineContext)
    {
        $cursor = $inlineContext->getCursor();

        $previous = $cursor->peek(-1);
        if ($previous !== null && $previous !== ' ') {
            return false;
        }

        $saved = $cursor->saveState();

        $cursor->advance();

        $handle = $cursor->match('/^[a-z0-9\+\-_]+:/');

        if (!$handle) {
            $cursor->restoreState($saved);

            return false;
        }

        $next = $cursor->peek(0);

        if ($next !== null && $next !== ' ') {
            $cursor->restoreState($saved);

            return false;
        }

        $key = substr($handle, 0, -1);

        /* Create the emoji span. */
        $html = new HtmlInline('<span class="emoji">:' + $key + ':</span>');
        $inlineContext->getContainer()->appendChild($html);

        return true;
    }
```

Any reason why this isn't adding the inline HTML? I can't see why not. The code is running down to that point so I don't understand what the issue is.

**Comment by jbrooksuk** [comment]
If you're writing an Emoji extension, you might be interested in our [AltThree/Emoji](https://github.com/AltThree/Emoji) extension.

**Comment by muhghazaliakbar** [comment]
i have same issue about `HtmlInline`
