### ISSUE TITLE
target _blank for link

### ISSUE THREAD

**Issue by cmnstmntmn** [thephpleague/commonmark#267]
is there a way to add target attribute to links ?

**Comment by colinodell** [comment]
Yes, you'll need to set the `data['attributes']['target']` on the `Link` element.  You'd probably want to use a [document processor](http://commonmark.thephpleague.com/customization/abstract-syntax-tree/#document-processor) for this.

Take a look at the `ExternalLinkProcessor` code example on that page - you'd simply need to duplicate that code and make this change:

```diff
- $url = $node->getUrl();
- if ($this->isUrlExternal($url)) {
-     $node->data['attributes']['class'] = 'external-link';
- }
+ $node->data['attributes']['target'] = '_blank';
```

The code listing below that one shows how you connect your new document processor into the engine to make it work.

**Comment by cmnstmntmn** [comment]
aha, thank you. i'll have a look
