### ISSUE TITLE
the rightway to use in blade laravel

### ISSUE THREAD

**Issue by mistercatformation** [thephpleague/commonmark#274]
Hi,

this is currently my way to use it on Laravel:

in Controller pass the class to view
return view('view.blade', ['post' => $post, 'converter' => new CommonMarkConverter()]);

since i want to use other attribute on post not just the content that i want to markdown.

And in blade
```
{!! $converter->convertToHtml($post->subject) !!}
```

i assume the method convertToHtml($var) already escape the text, so i dont have to use blade {{ }}
if i write a code like simple <script>alert('x'); </script> not in triple single-quote , it will run the script.

is this the right & best way?

**Comment by GrahamCampbell** [comment]
You could use my markdown package for this. It supports `Markdown::...` and, also having `.md.blade.php` files :)

**Comment by GrahamCampbell** [comment]
It's listed on the integrations: https://github.com/thephpleague/commonmark#integrations.

**Comment by colinodell** [comment]
I second @GrahamCampbell's recommendation.

But if you still prefer to implement it yourself,

> i assume the method convertToHtml($var) already escape the text

This is **not** the default behavior - you'll want to configure the `html_input` option.  See http://commonmark.thephpleague.com/security/ for more details.

**Comment by GrahamCampbell** [comment]
> This is not the default behavior - you'll want to configure the html_input option.

Yeh, and this can be configured from the markdown.php config file in the laravel integration if you choose to use that.
