### ISSUE TITLE
tabulator problem

### ISSUE THREAD

**Issue by TomAtom** [thephpleague/commonmark#279]
When is in string "tabulator", last two characters of word, whitch is after tabulator are duplicated.

On input in common mark is (between "aa" and "1234" is tabulator):
`aa	1234`

And on ouput is:
`aa	123434`

**Comment by colinodell** [comment]
Thanks for the report!  I'll work on resolving this bug soon.

**Comment by TomAtom** [comment]
@colinodell Thank you for quick solution.
