### ISSUE TITLE
How would one render an image inside a div?

### ISSUE THREAD

**Issue by wouterds** [thephpleague/commonmark#285]
Hi,

I created a custom CommonMark extension using an InlineParser (based on the emoji example from AltThree/Emoji). So if I write `:media:1:` it will render the media object with id 1 for example.

```php
// $context = instance of League\CommonMark\InlineParserContext

// Create image
$image = new Image(Storage::url($media->path), $media->label);
$image->data['attributes'] = ['class' => 'media-object'];

// Add image
$context->getContainer()->appendChild($image);

return true;
```

Now, that works, but it's wrapped in a paragraph. **I'd like to wrap the image with a div instead of a paragraph.** I've been looking for hours through documentation and examples but there's little to find about BlockParsers.

What I've tried so far in the BlockParser is the following, however, that doesn't render anything.
(And it does get to this part in the code.)

```php
// $context = instance of League\CommonMark\ContextInterface

// Create block
$block = new HtmlBlock(HtmlBlock::TYPE_6_BLOCK_ELEMENT);

// Create image
$image = new Image(Storage::url($media->path), $media->label);
$image->data['attributes'] = ['class' => 'media-object'];

// Add image
$block->appendChild($image);

// Add block
$context->addBlock($block);

return true;
```

So I'm stuck, all help is welcome!
Thanks in advance!

**Comment by muhghazaliakbar** [comment]
need to use `HhtmlInline` to render custom inline tag, but i also write issue for this because the `HtmlInline` didnt work :D #283

**Comment by wouterds** [comment]
@muhghazaliakbar: I'm afraid using anything with the InlineParser will wrap it in a paragraph (because it *is* inline). Just did a quick test using HtmlInline element and an h1 as contents. This renders, as expected, the following: `<p><h1>Test</h1></p>`.

**Comment by wouterds** [comment]
*Update*

If I change `$block = new HtmlBlock(HtmlBlock::TYPE_6_BLOCK_ELEMENT);` with `$block = new Paragraph();` it does work, and is obviously wrapped inside a paragraph. So in order to get in a div I assume I have to create my own `Div` block element a la the `Paragraph` one?

**Comment by wouterds** [comment]
I can confirm that it works once I created my own Div block element and Div block renderer. I'm assuming that's not included on purpose? Or can I submit a PR with these changes?

Or do you guys have an alternative / suggestions to work around this?

**Comment by wouterds** [comment]
**Update 3:**
I finally got everything working as I want!

What I did (I'm using it in combination with Laravel-Markdown from @GrahamCampbell) was creating a custom Block Element, `Media`. This is rendered using a custom `MediaRenderer` and is parsed using a custom `MediaParser` and this is all registered using a custom `MediaExtension` which is registered using the `markdown.php` config file from Laravel-Markdown.

So inside the Media Block Renderer I can give whatever contents I like to the HtmlElement, like so.

```php
class MediaRenderer implements BlockRendererInterface
{
    public function render(AbstractBlock $block, ElementRendererInterface $htmlRenderer, $inTightList = false)
    {
        if (!($block instanceof Media)) {
            throw new \InvalidArgumentException('Incompatible block type: ' . get_class($block));
        }

        // Get media object (this is an Eloquent model that was fetched earlier on)
        $media = $block->getMedia();

        // Contents
        $contents = '';
        $contents .= '<div class="media-object__spacer" style="padding-bottom:' . $media->ratio * 100 . '%">';
        $contents .= '</div>';
        $contents .= '<img class="media-object__image" src="' . Storage::url($media->path) . '" alt="' . e($media->label) . '">';

        // Create media object
        return new HtmlElement('div', ['class' => 'media-object'], $contents);
    }
}
```

So whenever I write `:media:1:` through my CMS now it'll render the following (in this case a media object with id 1) as seen below 😄 !
```html
<div class="media-object"><div class="media-object__spacer" style="padding-bottom:62.5%"></div><img class="media-object__image" src="/storage/media/uuvSVYq4BcBQ8HPfnPOAmjCgmmf4QO1PSGjgHNhb.jpeg" alt="&quot;Screen Shot 2017-05-17 at 18.06.02.jpg"></div>
```

**Comment by jchook** [comment]
Hey thanks for posting this. Very surprisingly, basic HTML rendering changes are not covered well in the documentation whatsoever. There are two examples and they're both for `InlineParserInterface`.
