### ISSUE TITLE
Why `%23` in `a.href` is decoded to `#`?

### ISSUE THREAD

**Issue by Hywan** [thephpleague/commonmark#287]
Hello,

We have an issue here https://github.com/hoaproject/W3/issues/135. We have this kind of links:

```markdown
[link](https://img.shields.io/badge/help-%23hoaproject-ff0066.svg)
```

that is converted to the following HTML:

```html
<a href="https://img.shields.io/badge/help-#hoaproject-ff0066.svg">link</a>
```

Which is not what we expect. The `%23` must not be converted to `#` in this case.

Are we missing something 😄?

Thanks for your great tool!

**Comment by colinodell** [comment]
This might be a bug with PHP's `rawurldecode()` function.  I'll see if I can find a better alternative which preserves `%23` in these cases.

**Comment by Hywan** [comment]
Thanks!

**Comment by Hywan** [comment]
cc @Metalaka @vonglasow @lyrixx

**Comment by colinodell** [comment]
Fixed via 7d91ca0.  I'll be releasing 0.15.6 with this fix once Travis confirms all the tests are passing.

**Comment by colinodell** [comment]
https://github.com/thephpleague/commonmark/releases/tag/0.15.6

**Comment by Hywan** [comment]
Sounds good, thanks :+1:!
