### ISSUE TITLE
Increasing minimum PHP version to 5.6 or 7.0

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#304]
I'm thinking of bumping the minimum PHP version to either 5.6 or 7.0.  This library already supports 5.6 -
 7.2 and we don't necessarily *need* any of the new features at this point in time though.  What are your thoughts?  Should we make the jump now or wait until we have a strong technical case for doing so?

(See also https://twitter.com/colinodell/status/947130490758234112)

**Comment by GrahamCampbell** [comment]
I think bumping to 5.6 right now makes sense. If you want to make use of PHP 7.0 features, then going to 7.0 instead of 5.6 makes sense also. Don't bump to 7.0 unless you want the features I think.

**Comment by colinodell** [comment]
Thanks for your thoughts!

I did a thorough re-review of everything that's changed since 5.4 and found that 5.6 was really the best candidate: it adds support for constant expressions which means `RegexHelper` no longer needs to be a singleton :)

PHP 7.0+ does really add anything we *need* right now.  Sure, scalar type hints and the syntactic sugar of `??` are nice, but they're not necessary at this time.

So 5.6 it is!

**Comment by GrahamCampbell** [comment]
👍
