### ISSUE TITLE
Convert to HTML without wrapping in an HTML element

### ISSUE THREAD

**Issue by chrisrollins65** [thephpleague/commonmark#312]
I've got an example where I want to use Markdown to convert HTML inside an HTML element without wrapping it in any tags. For example, I've got something like this:

`<span class="someClass" id="someId">**Bold text** normal text</span>`

I'd like to send just the string `**Bold text** normal text` to the `convertToHtml` function without it getting wrapped in `<p>` tags since it's already wrapped in my `<span>` tags.

Is there a way to do that? If not, what could we do to add that functionality? Would it require a custom block renderer/parser?

Or could this get baked in through the use of the `$inTightList` variable in render/renderBlock functions?

**Comment by glensc** [comment]
having the same problem in some other markdown implementation, I just went ahead and regexp-replaced the paragraph tag out:
- https://github.com/eventum/eventum/commit/1f7562ecdca866e45195331d431fa99a3429b40f

**Comment by colinodell** [comment]
I have created https://github.com/thephpleague/commonmark-ext-inlines-only which should provide the results you're looking for.

Please note that I don't have a large library of tests for this yet, so if you notice any unexpected behavior please file an issue in that repo (with your Markdown input) and we'll get it fixed!
