### ISSUE TITLE
Wrong version specified in 0.17.2

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#322]
I noticed after upgrading to 0.17.2, that https://markdown.unicorn.fail/benchmarks started showing `0.18-dev` as the version.

I know that updating this manually is a PITA.

Maybe this project needs a dedicated "build/deploy" script that automates this (and I'm sure other things) instead of having to remember to do this via a markdown checklist?

**Comment by colinodell** [comment]
This is what I get for releasing late at night...  I'll release 0.17.3 to fix this in a few minutes.

I do like the idea of creating a script as a long-term solution - just need to find the time and willpower :)

**Comment by markcarver** [comment]
Heh, I hear that 😄 

I'd offer a PR, but most of my automation/scripting power lies in Node.js/grunt/gulp/webpack etc.

Not sure what would be a good php based project build automator. I'm sure there's something out there.

Might look into this more this weekend if you haven't gotten to it by then.

**Comment by colinodell** [comment]
Alright this should be fixed in the latest release :)

**Comment by markcarver** [comment]
Yep, https://markdown.unicorn.fail is now showing 0.17.3
