### ISSUE TITLE
Test additional XSS inputs

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#338]
While I'm confident that 0.18.1 fixed the XSS issue described in #337, there are several other XSS inputs we could throw against league/commonmark to better test it - @GrahamCampbell suggested https://gist.github.com/JohannesHoppe/5612274.

This could be a main to do manually - perhaps we can automate this somehow?

**Comment by colinodell** [comment]
Implemented via https://github.com/thephpleague/commonmark/commit/439db71ed01fd02aa8f4982580e0b91cb809d219

**Comment by GrahamCampbell** [comment]
Nice. :)
