### ISSUE TITLE
Bablemark api broken

### ISSUE THREAD

**Issue by OpportunityLiu** [thephpleague/commonmark#340]
**Version(s) affected**: x.y.z

**Description**  

Any input to https://babelmark.github.io/ resulted in the same error.
![default](https://user-images.githubusercontent.com/13471233/54023078-fc17d700-41ce-11e9-8552-3317554a7aeb.png)

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by colinodell** [comment]
Thanks for the heads-up! It turns out I had a bad regex which broke the API - this has been fixed: https://github.com/colinodell/commonmark-babelmark2/commit/36afc986e5193ff1869e8a02506492acc7f4e973
