### ISSUE TITLE
[RFC] Drop support for PHP 5.6 and 7.0; add parameter and return types

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#346]
Solutions for #341 and #345 will likely break backward-compatibility and require extension authors to make changes, so **it seems like now would be the best time to drop support for PHP 5.6 and 7.0, and also implement parameter/return types throughout this project**.  This way, extension authors only have one (larger) set of changes to make instead of breaking BC in the next release **plus** another future release.

This would also put us much closer toward a potential v1.0 release.

If you are a contributor or extension developer please let me know your thoughts!

**Comment by colinodell** [comment]
@GrahamCampbell @pmjones @mnapoli @hason You maintain popular packages built on league/commonmark.  Implementing parameter/return types may impact your libraries, especially if they're custom extensions, so I'd appreciate your thoughts on whether you'd mind us bundling this breaking change with others in the upcoming major release (0.19).  I'm thinking this would be better than spreading BC-breaking changes across multiple releases.  I'd greatly appreciate your feedback, even if it's a simple :+1:.  Thanks!

**Comment by mnapoli** [comment]
@colinodell I use your package (thank you ❤️ ) in Couscous via FrontYAML. Here is the line where everything happens: https://github.com/mnapoli/FrontYAML/blob/master/src/Bridge/CommonMark/CommonMarkParser.php

It seems like it's all good for me!

**Comment by hason** [comment]
@colinodell That's great news! I'll make new versions of packages.

**Comment by pmjones** [comment]
We lock to specific CommonMark versions, so BC breaks should not affect us unexpectedly; and we are not opposed to making changes as needed for future releases. Thanks for the advance notice!

**Comment by colinodell** [comment]
Implemented via #350
