### ISSUE TITLE
Escape HTML attributes inside of the HtmlElement

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#354]
We're currently escaping the entities before passing them to the HtmlElement helper.  It would make more sense to do the escaping **inside** the class instead.

**Comment by glensc** [comment]
some context: https://github.com/thephpleague/commonmark/commit/6f16c6eb893f760d3b4f9a03c94c62653c4ac829#commitcomment-32949455

**Comment by colinodell** [comment]
Implemented via https://github.com/thephpleague/commonmark/commit/5f63bd34eded586adde4d2899fd92ac44676d8d6
