### ISSUE TITLE
ISO-8859-1 support is broken

### ISSUE THREAD

**Issue by tomsommer** [thephpleague/commonmark#361]
```
    ini_set('default_charset', 'ISO-8859-1');
    use League\CommonMark\CommonMarkConverter;
    use League\CommonMark\Environment;

    $environment = Environment::createCommonMarkEnvironment();
    $markdown = new CommonMarkConverter([], $environment);


    $text = 'foo gå `bling`-bar';

    $text = mb_convert_encoding($text, 'ISO-8859-1');

    var_dump($markdown->convertToHtml($text));
```

The above code returns 

```
<p>foo gå `.bling`-bar</p>
```

Seems UTF-8 is now required as input?

Version: 0.19.1

**Comment by colinodell** [comment]
It looks like the `Cursor` class may not be playing nicely with ISO-8859-1 encoding.  I'll add some unit tests for this particular encoding to figure out what's going wrong here.

**Comment by colinodell** [comment]
Yeah, unfortunately, it seems that the `preg_match()` function doesn't always play nicely with ISO-8859-1, particularly when the `/u` modifier is used (which makes sense).  Internally, we are making some assumptions that a Unicode-based encoding is being used, and other extensions also do the same.  I therefore think we need to enforce UTF-8 being used internally.

So the question becomes whether we should include some sort of "convenience layer" to make it easy to work with other encodings, or whether we should require developers to handle the encoding conversion themselves.

We do already have the `Converter` class (and its `CommonMarkConverter` subclass) which we could use for this purpose, perhaps by adding an optional `$encoding` parameter to the `convertToHtml()` function; we'd use that to convert the input to UTF-8 before use, and then back to `$encoding` when rendering.

Two potential issues with this:

1. Adding a new parameter here breaks our BC promise.
2. Do we make the default value `null` to enable auto-detection? This may work for common encodings but not others.

So I think that ultimately our two choices are:

1. Do nothing - you must convert the encoding yourself
2. Deprecate the `convertToHtml()` method and create a new one that includes that second parameter, considering the potential issues of auto-conversion mentioned above

Thoughts?

**Comment by tomsommer** [comment]
I think the best thing is to mimic the old functionality: You get the encoding back that you gave? So option 2 with auto-detection seem to be best?

In any case, BC is already broken because of whatever change was made to break ISO-8859-1
