### ISSUE TITLE
Fix Scrutinizer code coverage

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#375]
Scrutinizer CI is reporting that tests are failing and so coverage can't be logged.  This might be related to the `nightly` tests failing? Not 100% sure

**Comment by GrahamCampbell** [comment]
Is it expecting the correct number of runs in the config?

**Comment by colinodell** [comment]
Yep, but apparently the `7.4snapshot` and `nightly` jobs were sending failures to Scrutinizer before the code coverage from supported versions got send, causing it to (incorrectly) think the entire job failed.  This has been fixed via commit 39c6542c4cdf903d7b51ed55dc9388d1a167c3f9
