### ISSUE TITLE
Upgrading the (external) commonmark-attributes-extension to 1.0.0

### ISSUE THREAD

**Issue by nonoesp** [thephpleague/commonmark#380]
**Description**  

I've been using the [commonmark-attributes-extension](https://github.com/webuni/commonmark-attributes-extension) for a while and it breaks with commonmark `1.0.0`. I haven't been able to upgrade the package myself, as I believe this jump requires important changes.

(1) Would there be someone who can take a peek and let me know whether that kind of extension is still supported by the new Inline Parsers and Delimiter Processors architecture? I'd be willing to put some work to help upgrading it. As far as I've seen, this extension does a bit more than parsing ending and starting delimiters (say, `*emphasis*`).

(2) Are there any plans (and would it make sense) to incorporate this extension as one of commonmark's core extensions?

**Thanks so much in advance,**

Nono

cc @hason @colinodell @jdavidbakr

**Comment by colinodell** [comment]
That particular extension is not maintained by the PHP League, and it looks like there's [an issue over in that repo to track that upgrade](https://github.com/webuni/commonmark-attributes-extension/issues/17), so I'm going to close this.
