### ISSUE TITLE
Supported PHP versions

### ISSUE THREAD

**Issue by mmmilan** [thephpleague/commonmark#407]
I couldn't find any clear indications on what PHP versions are supported (apart from the changelog mentioning PHP 7.4), tried it on PHP Version 5.6.40-0+deb8u8 (it's some Debian LTS loved by our server operators) and failed:
`Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/p_dotti/webdata/vendor/league/commonmark/src/Environment.php on line 132`
Better late than never, could you please document the supported PHP versions?

**Comment by cebe** [comment]
Minimum required PHP version is 7.1 according to composer.json : https://github.com/thephpleague/commonmark/blob/75ebe65728cc148e51160eab3812a8ebdcefbcc7/composer.json#L23

**Comment by mmmilan** [comment]
Thank you, now I got the information I needed, but I don't think composer.json meant to replace documentation/readme requirements section.

**Comment by colinodell** [comment]
This has been added to the README :)
