### ISSUE TITLE
Can we disable lists which start with "+"?

### ISSUE THREAD

**Issue by egorsmkv** [thephpleague/commonmark#408]
**Description**  

Can we disable lists that start with "+"?

```
+   Red
+   Green
+   Blue
```

Lists doc: https://github.com/thephpleague/commonmark/blob/f18ebbe50dae14a472d8a76639c4116337968a8c/tests/benchmark/sample.md#lists

**Comment by colinodell** [comment]
Allowing `+` to denote bulleted lists is part of the [CommonMark spec](https://spec.commonmark.org/0.29/#bullet-list-marker), so we can't fully remove this support from the library, though we could potentially make it possible to configure or customize this for those who need it.  Could you tell me more about your particular use case for wanting to disable this?

**Comment by egorsmkv** [comment]
I am building forum software where people can send posts. I am using CommonMark to render posts. A person can send a post that has content "+", this means he/she agrees with something, for example, when quoting someone's post. But CommonMark transforms this into a list.

**Comment by colinodell** [comment]
Thanks!  I'll get this feature added to the next release :)

**Comment by egorsmkv** [comment]
Thank you very much for this!
