### ISSUE TITLE
CI coverage reporting broken

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/commonmark#410]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/2829600/73730432-a75a4480-472e-11ea-898a-b1d2fac6b805.png">

**Comment by colinodell** [comment]
This seems to be an issue with `scrutinizer/ocular`: https://github.com/scrutinizer-ci/ocular/issues/47

For now, I'll downgrade the version we use to avoid this bug.
