### ISSUE TITLE
Add the GFM converter in babelmark

### ISSUE THREAD

**Issue by stof** [thephpleague/commonmark#413]
The league/commonmark parser is already registered on https://babelmark.github.io/ (although using 1.2.0 currently rather than the latest 1.3.0).

It would be great if a second endpoint could be registered using the new GFM converter, to be able to compare its output.

**Comment by colinodell** [comment]
Thanks for the feedback!

I've upgraded the version used to 1.3.0 and have begun the process of adding the GFM variant to babelmark - I'll update this issue once it is available.

**Comment by colinodell** [comment]
The GFM converter has been submitted to the Babelmark registry: https://github.com/babelmark/babelmark-registry/pull/13  Once that's merged you should be able to see the results of our GFM converter alongside the other Markdown parsers.

**Comment by colinodell** [comment]
This has been completed!
