### ISSUE TITLE
Incorrect link processing if it contains brackets

### ISSUE THREAD

**Issue by Niklan** [thephpleague/commonmark#415]
**Version(s) affected**: 1.3.0

**Description**  
If link contains brackets, it's not processed.

**How to reproduce** 

```markdown
[Salt](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_(%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F))
```
Example that GitHub handle this: [Salt](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_(%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F))

**Possible Solution**  

Count opened brackets inside the link and find them closing. I guess the GitHub processing works this way:

- [Salt](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_(%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F))), ([Salt](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_(%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F))) — additional bracket at the end correctly detected
- [Salt](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F)) — I removed opening bracket inside the link and it also handles this as expected.

**Comment by GrahamCampbell** [comment]
Your example seems to parse correctly?

https://babelmark.github.io/?text=%5BSalt%5D(https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%25A1%25D0%25BE%25D0%25BB%25D1%258C_(%25D0%25BA%25D1%2580%25D0%25B8%25D0%25BF%25D1%2582%25D0%25BE%25D0%25B3%25D1%2580%25D0%25B0%25D1%2584%25D0%25B8%25D1%258F))
https://babelmark.github.io/?text=%5BSalt%5D(https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%25A1%25D0%25BE%25D0%25BB%25D1%258C_(%25D0%25BA%25D1%2580%25D0%25B8%25D0%25BF%25D1%2582%25D0%25BE%25D0%25B3%25D1%2580%25D0%25B0%25D1%2584%25D0%25B8%25D1%258F)))

**Comment by colinodell** [comment]
I agree, this seems to be parsing correctly, and consistently with other CommonMark parsers.

Please feel free to test your Markdown against the Babelmark tool mentioned above and/or https://spec.commonmark.org/dingus/. If you see the same output between the C or JS reference parsers and this library that means we are parsing it correctly per the spec.

**Comment by Niklan** [comment]
Thank you folks, you are right. I tested by direct call and works as expected. But to the end user it comes through many other layers (CMS) so I will search problem there. It's the only link which fails to convert and shows as is.

It's debug time :beetle: 😁 If I found something related to package I reopen the issue. Thank you again. Nice services for testing btw.

**Comment by Niklan** [comment]
Found that my link leads with `<p>` and this is broke it.

```
<p>[Salt](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BB%D1%8C_(%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F))</p>
```

Also confirms at `https://babelmark.github.io/?text=%3Cp%3E%5BSalt%5D(https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%25A1%25D0%25BE%25D0%25BB%25D1%258C_(%25D0%25BA%25D1%2580%25D0%25B8%25D0%25BF%25D1%2582%25D0%25BE%25D0%25B3%25D1%2580%25D0%25B0%25D1%2584%25D0%25B8%25D1%258F))%3C%2Fp%3E`

As I remember spec treats content in `<p>` as is. So this is must be correct. But where did this `p` comes from, this is my next question)
