### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#422]
CI tests aren't running :scream_cat:

**Comment by mfn** [comment]
They are, but the feedback loop github<>travis has issues

E.g. for https://github.com/thephpleague/commonmark/pull/420 there is https://travis-ci.org/github/thephpleague/commonmark/builds/670958523

I've seen the same issue on my public repos. Will probably just move to github actions 😄

**Comment by GrahamCampbell** [comment]
If you do their migration to travis-ci.com, then things should work?

**Comment by GrahamCampbell** [comment]
(from .org)

**Comment by GrahamCampbell** [comment]
https://travis-ci.com/organizations/thephpleague/migrate

**Comment by colinodell** [comment]
Thank you both! Migrating seemed to fix things :)

**Comment by mfn** [comment]
@GrahamCampbell nice info, is there any background why this is required?

**Comment by GrahamCampbell** [comment]
.com uses newer (2017...) apis, basically. .org should still work but it looks travis messed it up, so.

**Comment by colinodell** [comment]
Just kidding, it's broken again, and I've tried everything I could think of to fix this.  I've submitted a support ticket to Travis CI Support - hopefully they can point me in the right direction.

**Comment by mfn** [comment]
It really happens in a lot of projects, e.g. https://github.com/botman/botman/pull/1134#issuecomment-612458032

**Comment by GrahamCampbell** [comment]
Definitely seems to be travis' fault. Other CI services are having no trouble writing statuses.

**Comment by colinodell** [comment]
Ah, looks like they were doing maintenance: https://www.traviscistatus.com/incidents/xw5h6qv25mk1  Builds are magically working again! :tada:
