### ISSUE TITLE
Styling bugs

### ISSUE THREAD

**Issue by Veltinator** [thephpleague/commonmark#426]
**Version(s) affected**: latest

**Description**  
- When you want to style just a punctuation mark at the end of a word, the parser ignores to parse it. I know it's a very uncommon case, but I just figuerd it out.
**For example**: test\*.\* remains test\*
- When bold or italic styling includes a space at the end, the parsers ignores to parse this
**For example**: "te\*st \*" remains "te\*st \*"

I dont't know if these rules are correct in the commonmark guidelines, please correct me if this issue doesn't make sense :)

**Comment by GrahamCampbell** [comment]
The reference implementation of commonmark behaves the same as this library:

https://babelmark.github.io/?text=test*.*
https://babelmark.github.io/?text=te*st+*

**Comment by colinodell** [comment]
The [rules around emphasis parsing](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis) are quite complex, so I find it's always easiest to compare this library to other CommonMark libraries, including the C and JS references parses.  As Graham's links show, we follow the same rules and produce the same output, therefore this is the correct behavior per the CommonMark specification.
