### ISSUE TITLE
Create v1.4 docs

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#428]
- [x] Copy the `1.3` docs into a new `1.4` directory
- [x] Update all the version-related code in the docs to support multiple upcoming, current, previous, and outdated releases
- [x] Update the release checklist to always remember these steps once a new minor or major version is released

**Comment by colinodell** [comment]
This has been completed

**Comment by glensc** [comment]
wow. just wanted to say thanks for 1.4 release!

I'm looking forward to use permalink plugin!

**Comment by glensc** [comment]
I also wonder, why the "funding" block disappeared from composer.lock:
- https://github.com/glensc/eventum/commit/92f7ae14f4b9337fec2d428ed6f9ec42c657c7d9
