### ISSUE TITLE
[2.0] Refactor AST implementation

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#429]
The current implementation has a few issues I'd like to address in 2.0:

 - [ ] The `$data` array is annoying to work with; let's use dflydev/dot-access-data instead
 - [ ] Some node elements use the generic `$data` array, some have special-purpose member vars, others use both - would be nice to have some consistency here
 - [ ] Some parts of our code accept `Node` types when those are almost always `AbstractBlock` instances. See if we need to move some methods between these and/or tighten up our type hints.
 - [ ] Some setter methods return `void`, others return `$this`.  We should standardize this.

Rejected ideas:

- ~~Move AST implementation into a separate package~~ (if we ever want to use it for html-to-markdown conversion, we'll likely bake that into this library in a future version instead)
- ~~Perhaps remove the responsibility for changing the AST (adding, replacing, removing nodes) to some other class, instead of having nodes do this themselves?~~ I think they're better off being kept as-is
- ~~Nodes don't have an interface~~ Because of the previous item, I don't think it's valuable to mock or implement AST manipulation methods. We'll keep the abstract base class in 2.x
- ~~Modifying the AST during node traversal (with `NodeWalker`) can sometimes lead to Nodes being skipped~~ Moved to #443

**Comment by markcarver** [comment]
Is this still a 2.0 issue? Should we create a new 3.0 milestone for this?

**Comment by colinodell** [comment]
I've refined the list and still plan to implement the remaining items in 2.0.

**Comment by markcarver** [comment]
> * [ ]  The `$data` array is annoying to work with; let's use dflydev/dot-access-data instead

I was wondering if we should also implement a special "Attributes" object inside of that as well though. Often times, HTML attributes tend to need a little extra handling (i.e. classes) than just a straight-up FIFO "array" of values.

Perhaps you can take some inspiration from what I did here:

https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/Attributes.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeBase.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeArray.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeBoolean.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeClasses.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeData.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeDataValue.php
https://git.drupalcode.org/project/plus/-/blob/8.x-4.x/src/Utility/AttributeString.php

**Comment by colinodell** [comment]
I do plan to have some minimal handling.  In a nutshell, we're going to assume that attributes can either be a `string`, `string[]` (i.e. classes), or `true` (i.e. `checked` or `required`).

The `Data` class itself won't know anything about this.  But we would establish the convention that things like classes should be added via `$data->append()`.

The `HtmlElement` class will have most of the knowledge:

| If the attribute value is a | Then we will |
| `string` | Output it as-is |
| `string[]` | Join all unique values with spaces |
| `true` | Add the attribute name without a value |

This should suit most of the uses case we care about while still being flexible (aka "dumb") enough to allow for any other cases without too much trouble.
