### ISSUE TITLE
[2.0] Re-organize classes

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#432]
The file structure of this project hasn't changed much since version [0.5.0](https://github.com/thephpleague/commonmark/tree/0.5.0/src) - several things are "dumped" into the source root, and other things are not properly grouped based on their purpose.

Let's aim to solve this in v2.0.

**Comment by colinodell** [comment]
Changes have been implemented via 24d6071.  I don't anticipate any other changes at this time.

**Comment by glensc** [comment]
perhaps rename branch "latest" to "v2.0.x", as I was almost panicking what I'm doing wrong that I do not have `$link->data->set()` method that I saw on web:

- https://github.com/thephpleague/commonmark/blob/267e25d77a4efd29fd8802f01eef8178067b4e53/src/Extension/ExternalLink/ExternalLinkProcessor.php#L79
- https://github.com/thephpleague/commonmark/blob/267e25d77a4efd29fd8802f01eef8178067b4e53/src/Extension/ExternalLink/ExternalLinkProcessor.php#L18

**Comment by glensc** [comment]
and namespace like `CommonMark\Extension\CommonMark` is confusing!

**Comment by colinodell** [comment]
> perhaps rename branch "latest" to "v2.0.x", as I was almost panicking what I'm doing wrong that I do not have $link->data->set() method that I saw on web:

We renamed `master` to `latest` as part of #502. We are setting a branch alias in composer.json too:

https://github.com/thephpleague/commonmark/blob/44a6865/composer.json#L102-L106

We'll split off a `2.0` branch once we get closer to releasing `2.0.0`.

> and namespace like `CommonMark\Extension\CommonMark` is confusing!

Unfortunately, there's no getting around the fact that we have an extension containing CommonMark-only functionality.  In `1.x` this extension was called `CommonMarkCoreExtension` and its parsers/renderers were stored separately.  In `2.x` we're storing both together, so naming the CommonMark-specific extension `CommonMark` seemed to make the most sense.

**Comment by glensc** [comment]
@colinodell just that "latest" is very confusing in the sense that if 1.5 is still maintained "latest" release is from 1.5.x not from 2.x :)

"master" did not create a resemblance that it's a recent release :)

"latest" should be perhaps a moving tag.

I suggest using "main" if don't want to use version as a branch, as that's what everybody else is doing;
- github
- git
- gitlab

**Comment by colinodell** [comment]
Yeah, we settled on `latest` before the community eventually rallied around `main` as the new standard.  I'm not opposed to changing our branch name to `main` to better align with them, but it will break some URLs to things like `CHANGELOG.md`, so I'm not in a rush :upside_down_face:   I do appreciate the suggestion though!  We'll get it changed eventually :sweat_smile:
