### ISSUE TITLE
[2.0] Consider bumping minimum PHP version

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#434]
Determine if we could benefit from requiring a newer version of PHP.  For example, could we make use of 7.2's type widening or 7.4's typed properties?

My gut says we'll likely stick with PHP 7.1 or 7.2 for now and revisit this shortly before releasing 2.0 alpha/beta versions.

**Comment by iansltx** [comment]
Depends on when the release is expected to land. Seems reasonable to bump up to at least whatever PHP version is in security fix mode...and this is me being selfish about projects that are currently 7.2 but will get bumped to 7.4 before 7.2 goes EOL.

**Comment by GrahamCampbell** [comment]
7.2.5 might be a good shout. It's the version of PHP which ships with Ubuntu 18.04 LTS, and is the minimum PHP version of Laravel 7 and Symfony 5. I think it's a pretty reasonable base line version these days for any largely used projects. PHP 7.4 might be too soon for 2020.

**Comment by colinodell** [comment]
The minimum version for 2.x has been bumped to 7.2.5.  The typed properties and covariance/contravariance of 7.4 would still be super nice, but perhaps we'll save that for a future 3.x version?  We'll see :)

Closing this for now.

**Comment by GrahamCampbell** [comment]
Heh, I don't think typed properties have much use unless they are used on mutable public properties with is not such a common thing for libraries. Otherwise, all they do is cause a runtime performance degradation due to typechecking. Better to use phpdoc and a static analyzer in most cases.
