### ISSUE TITLE
Stricter coding standard

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#435]
While I do love StyleCI and hope to keep it, I'd like to augment that with something a little stricter and PHPCS-based.

**Comment by GrahamCampbell** [comment]
You can always enable more rules on StyleCI, and if there's something missing you'd like to see, it could be implemented. :)

**Comment by colinodell** [comment]
I'm going to temporarily set StyleCI to use `psr1` because I don't know how to configure it to match the new PHPCS code style I want to use (largely based on Doctrine's): https://github.styleci.io/analyses/D2Wvdn
