### ISSUE TITLE
[2.0] Revisit event implementation

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#436]
We've rolled our own event dispatching in order to keep things simple, but I'd like to revisit this for 2.0 and see if there's an alternative approach we could benefit from instead - ideally one of the following:

 - Determine that our approach is fine and keep it as-is
 - Leverage PSR-14 (if it makes sense and community adoption seems high - needs more research)
 - Require a popular package like `symfony/event-dispatcher` (or maybe support multiple?) but allow a wide of constraints

**Comment by markcarver** [comment]
Is this still a 2.0 issue? Should we create a new 3.0 milestone for this?

**Comment by markcarver** [comment]
So, just saw that the league has its own event implementation (very similar to what this project's doing now):

https://event.thephpleague.com

I think it makes more sense to dogfood and depend on this rather than something else.
