### ISSUE TITLE
[2.0] Improve node traversal

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#443]
Using the `NodeWalker` to find certain nodes can be overly verbose.  It would be nice if we could use something more like this:

```php
foreach ($document->findAll(Link::class) as $link) {
    // ...
}
````

Or maybe take it a step further and allow composition of different types of queries:

```php
$query = Query::orExpr(
    Query::type(Code::class),
    Query::type(IndentedCode::class),
    Query::type(FencedCode::class)
);

foreach ($document->query()->findAll($query) as $code) {
    $this->addSyntaxHighlighting($code);
}
```

The former example is pretty straight-forward to implement, but I'd love to hear feedback on whether the latter would be useful to anyone (or if it's more hassle to implement than it's worth)

(Somewhat related to #429)

**Comment by markcarver** [comment]
The latter seems like it would be more efficient as I would assume it would only do a single traversal, whereas it would require three `foreach` loops to achieve the same result, yes?

**Comment by markcarver** [comment]
Is this still a 2.0 issue? Should we create a new 3.0 milestone for this?
