### ISSUE TITLE
Improve types

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#444]
This library uses some types that are too generic (like `array`, for example).  Let's focus on replacing these with better types.  Some of this might be doable for 1.4, others may have to wait for 2.0 if they break BC.

**Comment by GrahamCampbell** [comment]
PHPStan can be configured to warn about array types that are not specific enough if you want software to let you know where these cases are. ;)

**Comment by colinodell** [comment]
Everything that can be easily implemented in 1.4 has been, so adjusting this to 2.0 so we can do more cleanup and ensure we have proper parameter & return types everywhere.

**Comment by colinodell** [comment]
This has been implemented in `master`.  The only remaining types I want to re-examine deal with configuration, but that's covered under #447, so I'm going to close this issue.
