### ISSUE TITLE
Website Display Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/commonmark#450]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2829600/79684236-9eeeb180-8227-11ea-82bf-eeeebe2b779a.png">
<img width="753" alt="image" src="https://user-images.githubusercontent.com/2829600/79684239-a44bfc00-8227-11ea-9cf8-a302e8b98897.png">

**Comment by colinodell** [comment]
I'm terrible at frontend development.  If anyone is comfortable using Jekyll and wants to help fix this I'd appreciate it!

Basically:

 - Check out the `master` branch of this repo
 - `cd` into the `docs` directory
 - Run `bundle install` or whatever it is that installs Ruby dependencies
 - Run `bundle exec jekyll serve` to execute Jekyll - it'll give you a URL to preview the site which auto-updates as you make changes
 - Fix the issue
 - Commit the issue and push up a PR
 - Have my sincere gratitude :wink:

**Comment by colinodell** [comment]
Fixed via https://github.com/thephpleague/commonmark/commit/6973ca4dccbc3eeca5e9152a33625d63176793ec

**Comment by GrahamCampbell** [comment]
Is the text meant to be so close to the top of the screen on the homepage?

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2829600/80318932-76f1e600-8805-11ea-869b-67de49db2fcf.png">

Maybe something like this would look better:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2829600/80319013-04cdd100-8806-11ea-9bf5-ea9eedf61b9c.png">


---

The display issue on the docs, however, does seem to be fixed now. Good job. :+1:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2829600/80319027-19aa6480-8806-11ea-9d7f-e17d0397399b.png">

**Comment by colinodell** [comment]
Good call!  I've deployed some styling changes to address that.
