### ISSUE TITLE
1.4 class aliases for interfaces breaking

### ISSUE THREAD

**Issue by GrahamCampbell** [thephpleague/commonmark#452]
**Version(s) affected**: 1.4.0

**Description**  

It appears that using class aliases for the old interface breaks dependency injection in Laravel.

https://github.com/GrahamCampbell/Laravel-Markdown/runs/600642515?check_suite_focus=true

**Comment by colinodell** [comment]
Sorry about that!  I tried aliasing it the same way Symfony does, but either I missed a step or perhaps DI containers don't play nicely with this approach.  Either way, I've got your fix merged in as 2b09c7a89f0d58e2c835e9b1575bf332483cfa1a and will release this as 1.4.1 once the tests pass.

**Comment by colinodell** [comment]
1.4.1 has been released: https://github.com/thephpleague/commonmark/releases/tag/1.4.1  Thanks again for catching this!
