### ISSUE TITLE
Feature Request: Allow Heading Permalink IDs to be generated using a callback

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#460]
Pretty straight forward, the ability to generate an ID for a header permalink using a callback rather than just static prefix would be extremely useful.

**Comment by colinodell** [comment]
Do you mind sharing a sample use case to help me better understand how this might be used?

**Comment by markcarver** [comment]
Suffice it to say, the "DefaultSlugGenerator" is fairly basic. It also implies that this can be replaced, but to do so requires manually implementing a standalone class and manually passing said class as a constructor parameter of that processor, requiring the manual recreation of the extension.

We already have a header ID generator that simplifies and strips out unnecessary verbiage and keeps track of existing IDs. Similar to https://git.drupalcode.org/project/markdown/-/blob/8.x-2.x/markdown.api.php#L99-100, we'd also like to store this header info so we can abstract it outside the body of the page into say, a fixed aside.

I just think it'd be easier to check for a callable setting that we can introduce via hooks, rather than having to go through the whole ordeal above.

This is semi-related/similar to solving the TOC issue by manually saving/recreating them (while generating the slug), so maybe there's a way to do this as well as "store" the generated TOC using said IDs somewhere? Not sure how #459 would fit into this exactly, but what happens if "placeholder" is used but not placeholder is actually used? Is this TOC extractable somehow so we can store/show it elsewhere?
