### ISSUE TITLE
Feature Request: Allow InlineMentionParser to be a little more dynamic

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#473]
**Description**  
Currently, in Drupal, we're having to reimplement this class to allow it to be a little more flexible so we can multi-purpose it. While we can certainly keep this up in our project, I figured these small additions might be something you'd be interested in porting upstream. If so, we wouldn't have to maintain our own version any longer.

Specifically, in two areas:

1. Dynamic symbol:
    - https://git.drupalcode.org/project/markdown/-/blob/1841fcb2d629ec40c8e83a3add861d2c871a36d2/src/Plugin/Markdown/CommonMark/Extension/InlineMentionParser.php#L45-46
    - https://git.drupalcode.org/project/markdown/-/blob/1841fcb2d629ec40c8e83a3add861d2c871a36d2/src/Plugin/Markdown/CommonMark/Extension/InlineMentionParser.php#L74
2. Dynamic link pattern handling (allowing a callable to be passed instead):
    - https://git.drupalcode.org/project/markdown/-/blob/1841fcb2d629ec40c8e83a3add861d2c871a36d2/src/Plugin/Markdown/CommonMark/Extension/InlineMentionParser.php#L108-126

This allows us to, more easily, provide multiple ways to "map" an `@` inline mention (entity, github, twitter and custom) as well as `#` (entity, custom):

- https://git.drupalcode.org/project/markdown/-/blob/1841fcb2d629ec40c8e83a3add861d2c871a36d2/src/Plugin/Markdown/CommonMark/Extension/AutolinkExtension.php#L298-327
- https://git.drupalcode.org/project/markdown/-/blob/1841fcb2d629ec40c8e83a3add861d2c871a36d2/src/Plugin/Markdown/CommonMark/Extension/AutolinkExtension.php#L201-250
- https://git.drupalcode.org/project/markdown/-/blob/1841fcb2d629ec40c8e83a3add861d2c871a36d2/src/Plugin/Markdown/CommonMark/Extension/AutolinkExtension.php#L252-289

**Example**  
<img width="1509" alt="Screen Shot 2020-05-12 at 7 34 18 AM" src="https://user-images.githubusercontent.com/351902/81692667-5d1aea80-9424-11ea-8258-1fd480fabb9f.png">

**Comment by markcarver** [comment]
Perhaps, instead of this being thought of as just a "mention" parser, we can consider this a "token" parser?

It would certainly help prevent the existing constructor BC breakage, a new class should be created `InlineTokenParser` which `InlineMentionParser` could then extend from to provide the default `@` symbol.

**Comment by colinodell** [comment]
I really like this idea and would love to implement this here! Let me see what I can do 😉

On a side note, I love working with the Drupal module! You've done an excellent job making it easy to implement and configure. I'm currently using it on colinodell.com and it works flawlessly.

**Comment by markcarver** [comment]
That's always great to hear! I've seen you around some issues in the past on d.o, but wasn't sure how involved with Drupal you actually were. We have a `#markdown` slack channel if you feel like joining: https://drupal.slack.com/archives/C012JG7EWKU

Now that I've more or less finally got the module to a stable point, I'd even be willing to offer co-maintainership if you'd like. I only hesitated in the past because even I wasn't sure what the end product was going to be yet and didn't think stepping on each other's toes would be helpful hehe

**Comment by colinodell** [comment]
I'm not as active with Drupal as I am elsewhere, but I do like to keep tabs on how people are using this project and what I can do to improve things for those users.

I appreciate the offer of co-maintainership, but honestly, I don't think I have enough time or Drupal-specific experience to be an effective co-maintainer.  But I'm more than happy to contribute with ideas, feedback, and discussions like this one!  And I will definitely join you guys on Slack :wink:
