### ISSUE TITLE
Feature Request: Merge Attributes and Footnotes Extensions

### ISSUE THREAD

**Issue by markcarver** [thephpleague/commonmark#474]
Given that this project has now consolidated a ton of these rando extensions into itself, I think the last two remaining popular extensions should follow suit:

- [ ] https://github.com/webuni/commonmark-attributes-extension
- [x] https://github.com/rezozero/commonmark-ext-footnotes

x-ref:
https://github.com/rezozero/commonmark-ext-footnotes/issues/7

**Comment by colinodell** [comment]
I agree with footnotes, not sure about the attributes extension though.  While I definitely see the value in having that available here, I'm also very cautious about adding anything that's not rooted within the official CommonMark or GFM specs or implementations.

**Comment by markcarver** [comment]
Well, going by that rationale, then the footnotes extension isn't in either... either.

FWIW, [attributes](https://packagist.org/packages/webuni/commonmark-attributes-extension) has over 88k installs, compared to [footnotes](https://packagist.org/packages/rezozero/commonmark-ext-footnotes) which has just over 1.3k installs. It's an extension I use all the time if only to do simple things like assigning IDs to headers.

While I understand the desire to not conflate spec implementations, these are just extensions on top of the spec (which is essentially what GFM is as well)

If anything this would only help get it [accepted as part of the official spec](https://talk.commonmark.org/t/consistent-attribute-syntax/272) faster.

**Comment by markcarver** [comment]
Also, #421 isn't either...

**Comment by colinodell** [comment]
True, the specs don't have them, but the GFM _implementation_ does have [footnotes](https://github.com/github/cmark-gfm/blob/master/src/plaintext.c#L194), and their Markdown pipeline does support [emojis](https://github.com/github/cmark-gfm/issues/75#issuecomment-355440087).  For those reasons, I feel like it's reasonable to assume these are as close to a standard as we have right now, and any future official specification of those will likely be based closely on those implementations.

I'm still open to the idea of attributes, but I'd like to better understand some of the various implementations other Markdown flavors are using and where the CommonMark community might be leaning.

**Comment by colinodell** [comment]
Maybe for the attributes, we could provide different "flavors" of them?  That way, if an official variant comes out, we don't have to break BC - we just offer the new official flavor?

**Comment by markcarver** [comment]
> but the GFM _implementation_ does have [footnotes](https://github.com/github/cmark-gfm/blob/master/src/plaintext.c#L194)

Still, not part of the spec.

> Emoji is not implemented as part of our Markdown stack

lol I'm not trying to be nit-picky here, but... come on. 😝 

---

I'm just saying that attributes has just as much right as ^.

These are extensions, not spec.

I really don't know of any "flavors" of attributes. It's a very basic and straight forward syntax.

There are only two variations that I am aware of:

1. The original and Kramdown, which use a colon after an opening curly bracket:

https://python-markdown.github.io/extensions/attr_list/
https://kramdown.gettalong.org/syntax.html#attribute-list-definitions

2. Everything else:
https://github.com/webuni/commonmark-attributes-extension
https://michelf.ca/projects/php-markdown/extra/#spe-attr
https://www.markdownguide.org/extended-syntax/#heading-ids
https://www.npmjs.com/package/markdown-it-attrs
https://pandoc.org/MANUAL.html#extension-header_attributes

Subsequently, webuni/commonmark-attributes-extension based its implementation on the originals and even supports the colon, but makes it optional:

> You can assign any attribute to a block-level element. Just directly prepend or follow the block with a block inline attribute list. That consists of a left curly brace, **optionally followed by a colon**, the attribute definitions and a right curly brace:

I really don't see this changing or something "new" coming out. If it even makes its way into the spec, it'll likely be what is already widely used; which is this.

**Comment by colinodell** [comment]
@rezozero @hason Would either of you be opposed to us bringing a copy your footnote and attribute extensions into the main `league/commonmark` library under a BSD-3 license?  We'd of course keep your copyright and attribution in the file headers just like we did when we brought the Table extension into this project: https://github.com/thephpleague/commonmark/blob/1.5/src/Extension/Table/TableParser.php#L8

Keeping these most-common extensions within the main package also helps us ensure that the extensions stay compatible with newer versions before they're released - important since we're actively working on upcoming releases for 1.5 and 2.0 :tada: 

Just let me know :)

**Comment by hason** [comment]
@colinodell OK

**Comment by markcarver** [comment]
Maybe mentioning @ambroisemaupate directly would be better (actual committer of `rezozero/commonmark-ext-footnotes`).

**Comment by ambroisemaupate** [comment]
@colinodell Hello that’s an honor if you would like to bring `footnotes` extension into core lib. This is OK for @rezozero and for me. 

Future enhancements would be added via Github PR into `league/commonmark` repo ?

**Comment by markcarver** [comment]
> Future enhancements would be added via Github PR into `league/commonmark` repo ?

Yes

**Comment by colinodell** [comment]
Awesome! Thank you both for being open to this.  I'll work on bringing these in over the next weekend or two :wink:
