### ISSUE TITLE
[1.5] Release Goals & Tasks

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#477]
Creating this issue to track a few odds and ends

 - [x] Ensure changes to [1.5 docs](https://github.com/thephpleague/commonmark/commits/1.5/docs/1.5) are replicated into 2.0 docs
 - [x] Ask @markcarver to help test the 1.5 branch before tagging
 - [x] Modify 2.0 docs to show migration path from 1.5 -> 2.0 instead of 1.4 -> 2.0

**Comment by colinodell** [comment]
@markcarver The 1.5 branch is pretty much ready at this point.  If you wouldn't mind testing it out when you have the chance, I'd appreciate it!  Once you give the :+1: I'll get 1.5.0 tagged and released! :tada:

**Comment by markcarver** [comment]
I'll try to get to this later tonight, perhaps sometime tomorrow.

**Comment by markcarver** [comment]
I'm good with where things sit in the 1.5 branch. I've still got a lot of work to do on the Drupal side of things, but this is ready.
