### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#500]
A working list things I'd like to see change in the docs:

 - [x] Make it easier to see all the extensions in one table near the top of the page.  Right now we have two separate tables near the bottom.
 - [ ] Split the 2.0 upgrade docs into two sections: one for "consumers" and "integrators" who only need to know the most important bits, and another for "customizers" who write their own parsers/renderers/etc and need all the fine details.

**Comment by markcarver** [comment]
I can probably work on the first item in #499

**Comment by colinodell** [comment]
Yeah, if you don't mind, that would be great!
