### ISSUE TITLE
unescapeAndEncode throws a PHP Error on some inputs

### ISSUE THREAD

**Issue by yanmii-is** [thephpleague/commonmark#509]
**Version(s) affected**: 2.0@dev (Only tested this one)

**Description**  
Discovered through fuzzing. Calling `unescapeAndEncode` with garbage input makes preg_split return a `false` boolean on https://github.com/thephpleague/commonmark/blob/53d99fafeab948b56c834345c1d3aa6b4bc905f3/src/Util/UrlEncoder.php#L39 The program will then call `count` on a boolean on the next line, causing the following PHP Error: 
`
Error: [2] count(): Parameter must be an array or an object that implements Countable in /home/yanmii/GitHub/maho/vendor/league/commonmark/src/Util/UrlEncoder.php on line 33 in phar:///home/yanmii/GitHub/maho/php-fuzzer.phar/src/Fuzzer.php:433
`

**How to reproduce**  
Call unescapeAndEncode with the following `$uri` argument, for example
![crash_hex](https://user-images.githubusercontent.com/48454532/85647932-7bb50800-b697-11ea-8cb9-65ecd8971544.png)
*Hexadecimal view of the input*

Here's the [PHP-Fuzzer](https://github.com/nikic/PHP-Fuzzer) test I've generated to catch this error

```
<?php
/** @var PhpFuzzer\Fuzzer $fuzzer */
require_once "vendor/autoload.php";
$fuzzer->setTarget(function($input) {
  League\CommonMark\Util\UrlEncoder::unescapeAndEncode($input);
});
$fuzzer->setMaxLen(258);
```

**Possible Solution**  
Check if `$chars` is an array before calling `count($chars)`

**Comment by colinodell** [comment]
This library checked the encoding at point where Markdown is provided for conversion but not for one-of usages of this method.  I've resolved this in 4351e4b.

Thanks for catching this!
