### ISSUE TITLE
MentionExtension listener example

### ISSUE THREAD

**Issue by glensc** [thephpleague/commonmark#510]
https://github.com/thephpleague/commonmark/pull/501 added new `MentionExtension` and I was wondering, can you share snippet to listen to the rendering of `@handle`, so implementations could for example update notification settings based on the handle in their application.

**Comment by colinodell** [comment]
Thanks for the feedback!  I've added some basic information over at http://commonmark.thephpleague.com/1.5/extensions/mentions/#rendering
