### ISSUE TITLE
Allow more than one character to be used as a symbol for MentionExtension.

### ISSUE THREAD

**Issue by doZennn** [thephpleague/commonmark#514]
**Description**  
Allow multiple characters as a mention symbol.

**Example**  
Currently "symbol" can only be a single character. Would be great if we could use more than one character like so:
```php
$config = [
    'mentions' => [
        'user_url_generator' => [
            'symbol'    => 'u:',
            'regex'     => '/^[a-z0-9]+/i',
            'generator' => $userMentionGenerator,
        ],
    ]
];
```

**Comment by markcarver** [comment]
This, currently, isn't possible and will definitely require something outlined like in https://github.com/thephpleague/commonmark/issues/492#issuecomment-638206173
