### ISSUE TITLE
[Heading Permallink]: Define levels

### ISSUE THREAD

**Issue by joshbruce** [thephpleague/commonmark#519]
**Description**  

At present there doesn't seem to be a way to configure the heading permalink extension to ignore some headers - compare to the table of contents extension.

Could be an array of header levels to include mapped to the markdown or html equivalents.

I have a site where the first line of HTML is always at the very top and is an H1 heading and I'd rather it not have this added. I use a workaround at present.

**Example**  

```php
// default
["heading_permalink" => [
  "levels" => [1, 2, 3, 4, 5, 6]
]

// skip h1
["heading_permalink" => [
  "levels" => [2, 3, 4, 5, 6]
]
```

Seems like it would be the most versatile approach.

**Comment by colinodell** [comment]
I like it!  This should be easy enough to implement for the upcoming 2.x release in a couple of months.

**Comment by joshbruce** [comment]
I should have put a note of the workaround I came to for this...guess I'll be figuring that one out again until 2.0 is released. lol

No pressure. Just laughing at myself.
