### ISSUE TITLE
PSR-14 compliance

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#523]
The event system we use is very similar to [PSR-14](https://www.php-fig.org/psr/psr-14/).  Perhaps we should make it fully PSR-compliant and allow users to optionally [use their own event dispatcher](https://packagist.org/providers/psr/event-dispatcher-implementation) if desired?

**Comment by markcarver** [comment]
Makes sense to me. No need to reinvent the wheel each time.

**Comment by colinodell** [comment]
Duplicate of #436
