### ISSUE TITLE
EmailAutolinkProcessor and UrlAutolinkProcessor does not account for IDNA domains

### ISSUE THREAD

**Issue by tomsommer** [thephpleague/commonmark#529]
IDN domains are not supported in the autolinkers.

foo@exæmple.com etc.

Commonmark 1.5.3

**Comment by colinodell** [comment]
Thanks for the report!

We're currently following the official GFM specification for what's considered an [auto-linkable domain name](https://github.github.com/gfm/#valid-domain):

 > A valid domain consists of segments of alphanumeric characters, underscores (_) and hyphens (-) separated by periods (.). There must be at least one period, and no underscores may be present in the last two segments of the domain.

GFM itself does not parse your example: https://babelmark.github.io/?text=foo%40ex%C3%A6mple.com

Although I certainly understand and appreciate that this definition is not a complete definition, the purpose of these specs are to ensure that all compliant parsers behave in the same way, so I'm very hesitant to deviate from those specs.  I'd therefore recommend [opening an issue with the GFM project](https://github.com/github/cmark-gfm/issues) to revise the definition of a "valid domain" and then we'll update this project to comply with that expanded definition.
