### ISSUE TITLE
Allow heading permalinks to be uniquely scoped per document, environment or manually

### ISSUE THREAD

**Issue by markhalliwell** [thephpleague/commonmark#539]
This is a follow-up to #531 

_Originally posted by @markcarver in https://github.com/thephpleague/commonmark/issues/531#issuecomment-676478985_:

> Although, the latter could maybe be subverted by maybe creating a new `heading_permalink/unique_slugs ` option that can take multiple values:
>
> `''` - None, uses the normal `SlugNormalizer`
`'document'` - Unique to new documents (resets `UniqueSlugNormalizer ` on `DocumentParsedEvent`)
`'environment'` - Unique to new environments (resets `UniqueSlugNormalizer` on extension construction or `setConfiguration`?)
`'manual'` - `UniqueSlugNormalizer ` remembers everything (i.e. unique to current PHP thread), requires manual reset

_Originally posted by @colinodell in https://github.com/thephpleague/commonmark/issues/531#issuecomment-678830197_:

> I'd be in favor of adding that kind of option, but with only two choices: `'document'` (default) or `'environment'`.
>
> I don't think we should do `''` because it doesn't align with GFM's behavior.
>
> I'm not sure how I feel about `'manual'.  I don't like that it requires global/static storage where two completely different sets of Environments have the ability to impact each other.  I can see why this might be useful - perhaps you have one `Environment` rendering a blog post and another (more-restricted one) to render user comments, and you don't want any collisions in slugs.  But in that case, I think I'd rather see some kind of slug prefix option.
>
> So building off your idea, I'd propose adding two options:
>
> - `heading_permalink/slug_scope`
> - `'document' - Unique to new documents
> - `'environment'` - Unique to new environments
> - `heading_permalink/prefix` - Any arbitrary string which should probably include a `-` character (defaults to `''`)
>
> We'd bring back something like the `UniqueSlugNormalizer` and it would handle:
>
> - Delegating to a child `TextNormalizerInterface` to create the slug
> - Tracking already-used slugs based on the scope in the first option above
> - Appending suffixes to make slugs unique, if needed
> - Maybe some functionality to prepend custom prefixes too?
> - Ability to add, list, and remove a list of "used slugs" (the CRUD idea)
>
> We'd expose an instance of that class via some getter method on the `HeadingPermalinkExtension`.
>
> What do you think?

_Originally posted by @markcarver in https://github.com/thephpleague/commonmark/issues/531#issuecomment-680945935_:

> I'm fine with just `document` and `environment` being the only two values/scenarios as long as the normalizer has some sort of CRUD in place. This would allow a CMS to implement a "manual" implementation easily enough without having to recreate a new environment each time it spits out an email or something with the same content.

**Comment by colinodell** [comment]
I've put together a potential implementation in #617 - any feedback would be appreciated!
