### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#553]
I'm not the greatest at writing documentation. Sometimes I don't fully proofread my work, and sometimes I assume that my readers already understand concepts I might not have explained sufficiently.  I'm also terrible at writing good CSS.

If you'd like to help me improve the documentation I'd greatly appreciate it!

## Who Should Help?

In the spirit of Hacktoberfest, contributions are welcome from anyone and everyone, especially if you are new to contributing to open-source projects!

## Tips

You can view the documentation online at https://commonmark.thephpleague.com/.  It is stored in this repository at https://github.com/thephpleague/commonmark/tree/latest/docs.

You can use Jekyll to spin up a local copy of the docs to test and preview your changes.  Assuming you already have [Ruby](https://www.ruby-lang.org/en/documentation/installation/), and [Bundler](https://bundler.io/) installed, simply run:

```bash
cd docs # Switch to the directory with the documentation site files
bundle install # Install Jekyll and other dependencies

bundle exec jekyll serve # Build the site
```

That last command will give you a link to preview the site in your browser.  Jekyll will watch for any changes you make to the site files, meaning you can simply reload your browser to see the changes in near-real-time.

## Acceptance Guidelines

Please keep the following in mind when suggesting changes to ensure your PR has a good chance of being quickly accepted:

**Examples of good changes:**

 - Fixing typos and other grammar issues
 - Fixing any broken code examples
 - Standardizing formatting between different pages
 - Expanding existing sections which don't have enough information
 - Improving my terrible CSS and fixing styling issues

**Please avoid:**

 - Submitting pull requests to any branch other than `latest`
 - Making edits that do not contribute in a meaningful way (for example, changing words like `color` to `colour`)
 - Editing documentation for older versions without also applying the same changes to newer versions
 - Sending one giant pull request with TONS of changes - smaller, more-focused PRs are easier and quicker to review

## Questions?

If you have any questions or want to suggest larger changes, please feel free to do so in this thread :)

**Thanks for contributing!**

**Comment by Rushikesh-ganesh** [comment]
i would like to contribute @colinodell
