### ISSUE TITLE
Failure handling unusual indentations.

### ISSUE THREAD

**Issue by anthonyryan1** [thephpleague/commonmark#57]
When I pass the following text into the parser (0.5.1) I get an exception rather than a rendered document.

# Minimal test case
<pre>
1. Line

        text

    test

2. Line

        text

# Header

* Word.
</pre>

# Stack trace
* [addLine](https://github.com/thephpleague/commonmark/blob/master/src/Block/Element/AbstractBlock.php#L247)
* [handleRemainingContents](https://github.com/thephpleague/commonmark/blob/master/src/Block/Element/IndentedCode.php#L95)
* [incorporateLine](https://github.com/thephpleague/commonmark/blob/master/src/DocParser.php#L157)
* [convertToHtml](https://github.com/thephpleague/commonmark/blob/master/src/CommonMarkConverter.php#L57)

---------

As far as I can tell, this does not affect the upstream parser, as the dingus renders it correctly. This may have been addressed in a newer version of the spec however (spec is up to 0.15).

**Comment by colinodell** [comment]
Thanks for reporting this issue!  There was a bug in our implementation (not related to the spec) which we've fixed.  It'll be included in version 0.6 which should be released in the next couple days.
