### ISSUE TITLE
RFC: Add markdown linting for docs/

### ISSUE THREAD

**Issue by pdelre** [thephpleague/commonmark#576]
**Description**  

#553 mentions a goal _"Standardizing formatting between different pages"_. To that end, the project could adopt a markdown linter for their docs. Adopting a linter will require various updates to the repo, its contributing documentation, and it's CI if it would like to be enforced.

1. Would the maintainers like an addition of a linter that checks the `docs/`, even with the (hopefully minimal) added burden of project configuration and maintenance changes?

I've generally used JS's [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint) as it integrates nicely with VSCode, but it was ported from ruby's [markdownlint/markdownlint](https://github.com/markdownlint/markdownlint), which aligns with the project's usage of Jekyll. The JS version has the added advantage of being used by GitHub's [Super-Linter Action](https://github.com/github/super-linter), further reducing the CI maintenance cost.  Unfortunately the two implementations are not compatible and cannot share configuration files.

2. Would the maintainers prefer `DavidAnson/markdownlint` or `markdownlint/markdownlint` as the chosen implementation?

**VS Code Example**  

![image](https://user-images.githubusercontent.com/1379248/95745096-7a1d4900-0c62-11eb-9e57-9b010850fc26.png)

**Comment by colinodell** [comment]
> Would the maintainers like an addition of a linter that checks the `docs/`, even with the (hopefully minimal) added burden of project configuration and maintenance changes?

Yeah, I'd be very interested in that!

> Would the maintainers prefer `DavidAnson/markdownlint` or `markdownlint/markdownlint` as the chosen implementation?

I like that `markdownlint/markdownlint` also uses Ruby (like Jekyll does), but honestly most people (myself included) probably won't run it locally.  So I'm okay using the JS-based version for easier CI integration and maintenance.

If you'd like to open a PR to add in the linting and any necessary fixes I'd really appreciate that :)
