### ISSUE TITLE
Question: Render custom unescaped tag in fenced code blocks

### ISSUE THREAD

**Issue by whoisyare** [thephpleague/commonmark#580]
Hi there.

I created a BlockRenderer & Parser which works completely fine and inserts safely a specific HTML Tag.
The point is, i want to make the %%%delimiter%%% working when used in fenced code blocks.

e.g.

```html
my awesome %%%html, which <u>is escaped</u>.
it works also with multiple lines! %%%
```

where %%% renders an unescaped <b> tag (once again, very safely in safe environment). Any ideas? Thanks.

**Comment by colinodell** [comment]
There's no clean way to do this in 1.x during the parsing step, but you could add an event listener for the `DocumentParsedEvent`, find all the fenced code blocks, and do some additional parsing at that time to un-escape the HTML contents.
