### ISSUE TITLE
Support bidi i.e. RTL

### ISSUE THREAD

**Issue by ArabCoders** [thephpleague/commonmark#584]
**Description**  
Add new flag to enable dir="auto" attribute on tags.
 
**Example**  
as of right now commonmark does not natively support adding attributes to rendered html tags, for example,
```html
<p>paragraph here</p>
<blockquote>
<p>text</p>
</blockquote>
```
if you start mixing languages such as arabic, hebrew, and farisi. you get one direction support. thankfully html5 added tag to allow the switching of text direction automatically using attribute `dir="auto"`.

so if possible could we add a new configuration option `[ 'enable_bidi' => true ]` which in turn add `dir="auto"` on  the block level html tags. so instead of the code above we got something like

```html
<p dir="auto">paragraph here</p>
<blockquote  dir="auto">
<p dir="auto">text</p>
</blockquote>
```

**Comment by markhalliwell** [comment]
I'm not sure if this is something that should really be added. Historically, yes the `dir` attribute has probably been around longer, but I'd argue that this kind of modification should be relegated to CSS as its presentational in nature.

You should be able to add this rule via CSS and have its directionality calculated using the P2 and P3 rules of the Unicode Bidirectional Algorithm (although, generally speaking, I tend to just add it in the global ruleset `*`, not `p`):

```css
p {
  unicode-bidi: plaintext;
}
```

There is also https://commonmark.thephpleague.com/extensions/attributes/ if you really want to add it via markdown:

```commonmark
paragraph here{dir=auto}

> text{dir=auto}
```

**Comment by ArabCoders** [comment]
Thank you for your response, i somehow missed `unicode-bidi` when i was reading the discussion on direction in whatwg thread about support for `dir: auto` in css, as it's stand now this is sufficient for my purpose.

I'll go ahead and close this feature request.

Thank you.
