### ISSUE TITLE
Links in Headings generate unrendered Markdown in TOC

### ISSUE THREAD

**Issue by sewid** [thephpleague/commonmark#587]
**Version(s) affected**: 1.5.7

**Description**  
If a heading contains a link, the TOC shows plain markdown code

**How to reproduce**  
Enabled extensions:

- TableOfContentsExtension
- TableExtension
- SmartPunctExtension
- HeadingPermalinkExtension
- FootnoteExtension

Render this markdown code
```
This is the site content

## This is a heading

## Another heading

## [Third heading](https://example.com) is a link
```

Returned TOC is:

```
This is a heading

Another heading

[Third heading](https://example.com) is a link
```

**Possible Solution**  

**Additional context**

**Comment by colinodell** [comment]
This has been fixed in [1.5.8](https://github.com/thephpleague/commonmark/releases/tag/1.5.8)
