### ISSUE TITLE
Escaped Asterisk in Heading becomes plain Markdown in TOC

### ISSUE THREAD

**Issue by sewid** [thephpleague/commonmark#588]
**Version(s) affected**: 1.5.7

**Description**  
If a heading contains an escaped asterisk, it gets rendered as plain markdown in the TOC.

**How to reproduce**  
Enabled extensions:

- TableOfContentsExtension
- TableExtension
- SmartPunctExtension
- HeadingPermalinkExtension
- FootnoteExtension

Render this content:

```
This is my text.

More text.

## Heading with a asterisk \*
```

The generated heading is:

```
Heading with a asterisk \*
```

**Possible Solution**  

**Additional context**

**Comment by colinodell** [comment]
This has been fixed in [1.5.8](https://github.com/thephpleague/commonmark/releases/tag/1.5.8)
