### ISSUE TITLE
Convert to Markdown

### ISSUE THREAD

**Issue by NigelGreenway** [thephpleague/commonmark#59]
Hi,

I am not sure if I am looking for something specific to what I need, but we currently use Markdown for our article text and so on. What I would like to do is parse the Markdown to HTML, save it in the database and then show the HTML within the template instead of parsing content on load.

With this, is there (I have had a quick look but cannot find anything) or will there be an ability to convert HTML back to Markdown?

Again, not sure if I thinking about this the right way but it can add a small load to converting different context on the same page.

Cheers

**Comment by philsturgeon** [comment]
While there are plans for a reverse markdown parser to come to the League, you don’t need one for this.

What I normally do is store a “source” and a “parsed” version of the article. When you create and edit, you store the markdown in the source field and put the parsed HTML version in the parsed fields. Then you just show parsed on the frontend, and use that to fill the edit form. When you save, override the parsed Markdown and you’re all set.

-- 
Phil

**Comment by NigelGreenway** [comment]
Mr sturgeon, thank you.
I never thought of that. Implementing that now.
Sent using Boxer
On 14 Jan 2015 13:31, Phil Sturgeon <notifications@github.com> wrote:While there are plans for a reverse markdown parser to come to the League, you don’t need one for this.



What I normally do is store a “source” and a “parsed” version of the article. When you create and edit, you store the markdown in the source field and put the parsed HTML version in the parsed fields. Then you just show parsed on the frontend, and use that to fill the edit form. When you save, override the parsed Markdown and you’re all set.



-- 

Phil



From: Nigel Greenway <notifications@github.com>

Reply: thephpleague/commonmark <reply@reply.github.com>>

Date: January 14, 2015 at 7:24:00 AM

To: thephpleague/commonmark <commonmark@noreply.github.com>>

Subject:  [commonmark] Convert to Markdown (#59)  



Hi,



I am not sure if I am looking for something specific to what I need, but we currently use Markdown for our article text and so on. What I would like to do is parse the Markdown to HTML, save it in the database and then show the HTML within the template instead of parsing content on load.



With this, is there (I have had a quick look but cannot find anything) or will there be an ability to convert HTML back to Markdown?



Again, not sure if I thinking about this the right way but it can add a small load to converting different context on the same page.



Cheers
