### ISSUE TITLE
External Links: Documentation: Misleading default for nofollow

### ISSUE THREAD

**Issue by Pyker** [thephpleague/commonmark#591]
**Version(s) affected**: Documentation for External Links extension on v1.5+

**Description**  
The documentation for External Links suggests that the default for nofollow, noopener, and noreferrer is `'external'` for all of them, but [the code](https://github.com/thephpleague/commonmark/blob/d440548ca5eafc084ac1a9d829ad5f7b41ff0cf7/src/Extension/ExternalLink/ExternalLinkProcessor.php#L88-L90) reflects that default for nofollow is in fact `''`/APPLY_NONE (empty string), whereas noopener and noreferrer are correctly `'external'`/APPLY_EXTERNAL.

This is the misleading/incorrect line:
![image](https://user-images.githubusercontent.com/528849/101664597-f1ddd900-3a43-11eb-8d92-cbc75b050ac9.png)

**How to reproduce**  
Not applicable.

**Possible Solution**  
Either change the mentioned line to reflect that `'external'` is the default for only noopener and noreferrer, and then mention that default for nofollow is `''`/(empty string) in the last option in that list, or create a separate paragraph mentioning what the defaults are.

**Additional context**  
Not applicable.

**Comment by markhalliwell** [comment]
I think this is actually a bug. External links should apply `nofollow` by default, and they were (originally) in #480, but then a follow-up commit changed that default, but didn't really give any explanation as to why this happened: https://github.com/thephpleague/commonmark/commit/3477aa213c3f1ed395872bb46e646c24b8dc5e34

I'm trying to remember any conversation as to why this may have occurred, but nothing is coming up.

**Comment by markhalliwell** [comment]
Doh. It was removed per my recommendation: https://github.com/thephpleague/commonmark/pull/480#discussion_r426173696

So yes, the docs need to be updated (perhaps also explaining why these are the default; SEO)

**Comment by colinodell** [comment]
Fixed via https://github.com/thephpleague/commonmark/commit/fc5a673be231c0a42fecc133fd273218a6a95f4a.  Thanks for the report!

**Comment by Pyker** [comment]
Thanks for the fix!
