### ISSUE TITLE
Naming of `DisallowedRawHTMLExtension` inconsistent

### ISSUE THREAD

**Issue by avdv** [thephpleague/commonmark#599]
**Version(s) affected**: 1.5 (and later)

**Description**  
According to the docs: https://commonmark.thephpleague.com/1.5/extensions/disallowed-raw-html/

You use the extension with

> ```
> use League\CommonMark\Extension\DisallowedRawHTML\DisallowedRawHTMLExtension;
> ```

But, this does not work, since the extension / class is actually called `DisallowedRawHtmlExtension` (`HTML` vs. `Html`).

**Possible Solution**  
The code examples / documentation should be fixed, I guess.

**Comment by colinodell** [comment]
Good catch!

**Comment by Jamesclark32** [comment]
I believe this pull request resolves this documentation problem.
Thanks for all the work on this package!
