### ISSUE TITLE
Markdown Extra

### ISSUE THREAD

**Issue by mnapoli** [thephpleague/commonmark#60]
Hi there!

I want to support Markdown Extra to be able to replace completely Parsedown with this package in Couscous. I'm guessing you don't want to add support for Markdown Extra in there right? (which would make sense, Markdown Extra ≠ CommonMark). Is there any plan on your side or anybody else for this? 

And if not and I have to get to it myself, do you think it can easily be done (hopefully the new architecture with the model will help). Do you have pointers/tips to get me started?

**Comment by colinodell** [comment]
It's definitely possible to extend CommonMark as of version 0.5 / 0.6.  You're correct though, we wouldn't want to include Markdown Extra within our package.  I'm not aware of anyone else who's working on this, so I'd definitely encourage you to create your own package which adds this functionality if you're interested.  (@dshafik has done exactly this to implement Markua support: https://github.com/dshafik/markua)

You'll want to start by creating a new [`Extension`](https://github.com/thephpleague/commonmark/blob/master/src/Extension/Extension.php).  This is a simple class which defines which parsers/renderers are initialized and in what order.  From there you'd just implement the different parsers/renderers you'd need (check out the existing classes for examples).

I hope that helps get you started.  I'm going to close this issue (to keep things tidy) but feel free to continue communicating here if you'd like.  Let me know if I can help answer any questions!
