### ISSUE TITLE
Heading Permalink Extension: remove setting of attribute "name" (because it's obsolote)

### ISSUE THREAD

**Issue by sokai** [thephpleague/commonmark#602]
**Description**  

I use this (great) library with the [Heading Permalink Extension](https://commonmark.thephpleague.com/1.5/extensions/heading-permalinks/) and while validating the HTML5 markup of my website with the [W3C Markup Validation Service](https://validator.w3.org/) I got the following `Warning`:
> The `name` attribute is obsolete. Consider putting an `id` attribute on the nearest container instead.

As far as I see, the `id` attribute ist correctly set-up, so I think you can simply remove the single line from the extension: 
https://github.com/thephpleague/commonmark/blob/1.5.7/src/Extension/HeadingPermalink/HeadingPermalinkRenderer.php#L55

And well, I ask if I should/can make the PR for this, too. :-)

Thanks a lot in advance + KR!

**Comment by markhalliwell** [comment]
If we're going to do this, then it would have to be in `2.0` as this is technically a breaking change (other people/code may currently rely on this). That being said, this is only a warning (not an error) so I'm not sure how big of a priority this really is or if we want to keep this (for BC reasons).

**Comment by aardgoose** [comment]
FWIW The validator for epubs at http://validator.idpf.org/ marks this as an error rather than a warning

**Comment by colinodell** [comment]
As of today, markdown like this:

```md
# Contact Us
```

Produces HTML like this:

```html
<h1><a id="user-content-contact-us" href="#contact-us" name="contact-us" class="heading-permalink" aria-hidden="true" title="Permalink">¶</a>Contact Us</h1>
```

Note how the `id` attribute is currently prefixed by default - this is to prevent user-submitted Markdown from unexpectedly conflicting with the site's stylesheet and being styled in unexpected (or perhaps even malicious?) ways.  If we were to remove the `name` attribute then we'd have to also prefix the `href` accordingly which could break existing links.  I don't think that's an acceptable break to add in 1.x.

For 2.0 I see two possible solutions:

## Prefix IDs and hrefs

Rename the `heading_permalink/id_prefix` configuration option to `heading_permalink/prefix` and use that same prefix for both IDs and hrefs.  But then the question becomes whether we should default to no prefix (which might break styles) or keep the current `user-content-` prefix (which would definitely break links).

## Provide JS snippet

We'd keep the current HTML output approach as-is (minus the `name` attribute) but provide a JavaScript snippet to check for prefixed IDs and scroll to them.  Something like this:

```js
if(window.location.hash) {
    var link = document.getElementById('user-content-' + window.location.hash);
    if (link) {
        link.scrollIntoView({behavior: 'smooth'});
    }
}
```

This snippet could either be provided in the documentation or as part of the HTML output.

I like that this approach avoids breaking styles or links, but I don't necessarily like that is requires either manual installation of JS or auto-injected JS.

----

What do y'all think about this?

**Comment by colinodell** [comment]
After thinking through this more, I think it would be best to make this breaking change in a way that's obvious and easily fixable by developers.

As I mentioned before, the big challenge is that the generated **URL fragments** and **IDs** are different in 1.x which works thanks to our use of the `name` attribute.  We deliberately prefix the IDs with `user-content-` like GitHub does to ensure that user-generated content can't conflict with IDs that serve other purposes in CSS or JS.  This is a security feature that we shouldn't break without consumers of this library knowing about it.  But if we remove `name` attributes those links will stop working.

I therefore propose we make `heading_permalink/id_prefix` required (remove the default), and add a new `heading_permalink/fragment_prefix` that is also required.  Removing the defaults will trigger immediate and obvious configuration validation errors that force the developers to weigh the security concerns and implement one of three options:

### Option 1: No changes to HTML output or links

Users who want to preserve the exact output and links would be instructed to do the following:

1. Set `id_prefix` to `'user-content'`
2. Set `fragment_prefix` to an empty string (`''`)
3. Install that JS on the page.

Once that's done, everything should keep working as-is.

### Option 2: No prefixes

If the developer trusts their users, they may choose to set both options to empty strings.  This will result in non-prefixed IDs (possible security/design concern) but existing links will continue to work as-is.

### Option 3: Same prefix for both

Alternatively, the developer may choose to use `'user-content'` as the prefix for both options.  This is the most secure solution and doesn't require adding any JS, but it will cause the URL fragments to change.

----

As much as I hate adding an extra hurdle for users who upgrade, I think it's probably the most responsible way of handling this.

Alternatively, I'd also be open to implementing those two config options but providing defaults of `'user-content'` (or perhaps just `'content'`) for both - basically opting everyone into Option 3 by default until/unless they notice and change it themselves.  This will definitely break the links but is better than opening up security risks.

What do you think?

**Comment by sokai** [comment]
@colinodell Sry for not replying to your excellent suggestions and thanks for implementing prefix. BR
