### ISSUE TITLE
Naming of DisallowedRawHTML inconsistent 

### ISSUE THREAD

**Issue by kinpoko** [thephpleague/commonmark#607]
**Version(s) affected**: 1.5

**Description**  

According to the docs: https://commonmark.thephpleague.com/1.5/extensions/disallowed-raw-html/
You use the extension with in Usage
> use League\CommonMark\Extension\DisallowedRawHTML\DisallowedRawHtmlExtension;

But, this does not work, since the extension / class is actually called DisallowedRawHtml (HTML vs. Html).

Something similar discussed in #599 .
But, that was not enough.

**Possible Solution**  

The code examples / documentation should be fixed, I guess.

Would you mind if I fix this bug?

**Comment by colinodell** [comment]
Yes, please feel free to submit a PR for this! Make sure you use the `latest` branch and not the `1.5` branch because all of our documentation is built using `latest`.

**Comment by kinpoko** [comment]
@colinodell Hi!
I did this #608 
Could you confirm that ?
