### ISSUE TITLE
Remove paragraph from list items in table of contents

### ISSUE THREAD

**Issue by froschdesign** [thephpleague/commonmark#613]
### Description

The generator for table of contents creates a paragraph for each list item:

https://github.com/thephpleague/commonmark/blob/37eb9a4c51b8d74b2fdf312d68c58eb506c9e269/src/Extension/TableOfContents/TableOfContentsGenerator.php#L108-L111

A list item can contain a `p` element and any other [flow content](https://www.w3.org/TR/html52/dom.html#flow-content-2) but the list item element defines and creates already a physically separated block. And since only one single link is included at a time, there is no need to add another block.

Regardless, additional spacing is added that needs to be removed to get a _normal_ list design.
This will also help with most frontend frameworks as they also do not use paragraphs in navigation.

### Current Behaviour

```html
<ul class="table-of-contents">
    <li>
        <p><a href="#level-2-heading">Level 2 Heading</a></p>
    </li>
    <li>
        <p><a href="#level-4-heading">Level 4 Heading</a></p>
    </li>
    <li>
        <p><a href="#level-3-heading">Level 3 Heading</a></p>
    </li>
</ul>
```

### New Behaviour

```html
<ul class="table-of-contents">
    <li>
        <a href="#level-2-heading">Level 2 Heading</a>
    </li>
    <li>
        <a href="#level-4-heading">Level 4 Heading</a>
    </li>
    <li>
        <a href="#level-3-heading">Level 3 Heading</a>
    </li>
</ul>
```

**Comment by colinodell** [comment]
This proposal makes sense to me.  We'll probably want to deprecate this in 1.x (perhaps even providing an option to disable it?) and then remove the `<p`> tags in 2.0.

**Comment by colinodell** [comment]
I've just remembered that 1.x does not allow rendering children that are a mix of inlines (like links) and blocks (like nested list blocks) when they co-exist as siblings in the AST.  This means that my proposed solution above won't work in 1.x.  I'll instead drop the `<p>` tags completely in 2.0 and ensure the changelog and upgrading guide highlight this change.

**Comment by froschdesign** [comment]
@colinodell 
Lightning-fast implementation, great!
I have already tested it and it works like a charm. (Version 2 as a target version is no problem for me.)

Thank you very much for that! 👍 👍 👍
