### ISSUE TITLE
[2.0] Drop support for PHP 7.2

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#625]
PHP 7.2 is end-of-life and [only 5% of our users](https://t.co/zKocU3e6Q7) currently use that version.  [PHP 7.3 also has a few features](https://www.zend.com/blog/guide-to-php-73) we might be able to leverage, like case-folding improvements.  Let's therefore drop support for 7.2 in the next major release.

Anyone stuck on 7.1 or 7.2 may continue using 1.x until they are able to upgrade.

**Comment by markhalliwell** [comment]
This would definitely be helpful for #546

**Comment by GrahamCampbell** [comment]
I don't think it would be unreasonable to make version 2.0 PHP 8 only. Version 1.0 is rock solid and people who need to stay behind on PHP 7 for a bit can keep using that. Related: Symfony 6 will be PHP 8 only.

**Comment by colinodell** [comment]
You're not wrong, but this library is used by many Drupal sites and [Drupal will support PHP 7.3](https://www.drupal.org/docs/system-requirements/php-requirements) until they release Drupal 10 next summer.

@markhalliwell I'll defer to you on this - do you feel comfortable with us going to PHP 7.4 or 8.0 for the 2.0 release?  Or would you prefer that we stick with 7.3+ for now?

(I do suspect I'll be releasing version 3.0 in a year or so, and that will definitely be PHP 8 only)

**Comment by colinodell** [comment]
Also, I plan to tag 2.0.0beta1 once I get feedback on the PHP version question :wink:

**Comment by markhalliwell** [comment]
It should be fine to require PHP 8 for `2.0`.

The Drupal Markdown module is already setup to handle specific library requirements.

The only requirement it uses for libraries like CommonMark is which major version it currently supports; specific PHP requirements are indirectly indicated by the requested version of the library's composer.json:

https://git.drupalcode.org/project/markdown/-/blob/8.x-2.x/src/Plugin/Markdown/CommonMark/CommonMark.php#L37-39

```php
 *         @InstallableRequirement(
 *           constraints = {"Version" = ">=0.4.0 <=1.0.0 || ^1.0 || ^2.0"}
 *         ),
```

We even do this with the bundled extensions. Take the Mention extension for example, while we support it, it isn't actually useable unless the installed CommonMark version is `1.5` or higher:

https://git.drupalcode.org/project/markdown/-/blob/8.x-2.x/src/Plugin/Markdown/CommonMark/Extension/MentionExtension.php#L27-31

```php
 *          @InstallableRequirement(
 *             id = "parser:commonmark",
 *             callback = "::getVersion",
 *             constraints = {"Version" = "^1.5 || ^2.0"},
 *          ),
```

Like @GrahamCampbell said, if people have lower PHP requirements then they can use the older versions until they want/can upgrade. This is how sites that are still using PHP 5 are doing it, they just haven't been able to upgrade to the latest CommonMark versions with all the new fancy features 😄 

IMHO, that is more than fair and honestly what Semver was designed to do from the get-go.

**Comment by colinodell** [comment]
Oh, that's awesome!  Thanks for that feedback.

https://github.com/thephpleague/commonmark/issues/671 :)
