### ISSUE TITLE
Mention extension does not play nicely with links

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#688]
**Version(s) affected**: 1.6 and 2.x

**Description**

Mention-like content inside of link text is not parsed correctly. For example, this input:

```markdown
Try [@driesvints](https://github.com/driesvints).
```

Produces this doubly-nested link:

```html
<p>Try <a href="https://github.com/driesvints"><a href="https://github.com/user/driesvints">@driesvints</a></a>.</p>
```

This is a violation of [the CommonMark spec](https://spec.commonmark.org/0.29/#link-text):

> Links may not contain other links, at any level of nesting. If multiple otherwise valid link definitions appear nested inside each other, the inner-most definition is used.

**How to reproduce**

Run the example above with this configuration:

```php
$environment->mergeConfig([
    'mentions' => [
        'username' => [
            'prefix' => '@',
            'pattern' => '[a-z\d](?:[a-z\d]|-(?=[a-z\d])){0,38}(?!\w)',
            'generator' => 'https://github.com/user/%s',
        ],
    ],
]);
```

**Possible solution**

I think this is happening because of how links are parsed lazily using the delimiter stack whereas Mentions are not.

Using the inner-most definition as proposed by the spec would not produce the expected output, and therefore our solution should find a way to avoid creating the doubly-nested AST elements in the first place.

One possible approach could be moving away from an inline parser to something that iterates through parsed `Text` nodes after inline parsing completes, and only creating mentions if those nodes do not exist inside of links.  This would probably work, but it's a BC break.

Other options may also be possible.

**Comment by colinodell** [comment]
> One possible approach could be moving away from an inline parser to something that iterates through parsed Text nodes after inline parsing completes, and only creating mentions if those nodes do not exist inside of links. This would probably work, but it's a BC break.

A more efficient solution that resolves this issue on both 1.x and 2.x without a BC break would be undoing any Mentions when the outer link is being parsed.  I was hoping to avoid `CommonMarkCoreExtension` needing to know about other extensions, but this seemed like the best solution when weighing all the pros and cons, so I'm fine making an exception this one time :)

**Comment by colinodell** [comment]
This has been fixed in [1.6.6](https://github.com/thephpleague/commonmark/releases/tag/1.6.6) and [2.0.0-rc2](https://github.com/thephpleague/commonmark/releases/tag/2.0.0-rc2)!

**Comment by driesvints** [comment]
Thanks a bunch @colinodell! 👏

**Comment by driesvints** [comment]
Just tested this and verified it's fixed 🙂
