### ISSUE TITLE
Extensions in repo

### ISSUE THREAD

**Issue by lukasoppermann** [thephpleague/commonmark#70]
Hey,

since it is really easy to add useful additions to this awesome parser and they should not be added to the core (since the core should always just stick to the commonmark standards), how about adding a folder or link doc to extensions?

I would think if anybody who wrote a good inlineparser sends a pullrequest in which the file is added to a new `extensions` folder, this would mean many people could just use those instead of rewriting everything.

Maybe if you feel this is to much work or puts you in the spot of having to maintain those extensions, you could just add a list to the docs, where people can send PRs to have their extension added.

Or maybe they could be added using the suggest tag in composer.
 
I hope you get what I mean, I think this could add a great deal of features to the parser without bloating it, because every feature would be opt-in as non come pre-enabled.

**Comment by colinodell** [comment]
I'd prefer to keep this project clear of non-core things as much as possible.

However, I do like the idea of having a central list of useful extensions.  I've created [a new wiki page] where we can list community extensions.  I've also linked to this page from the README.

Thanks for the suggestion!

**Comment by colinodell** [comment]
Woops, messed up that wiki link: https://github.com/thephpleague/commonmark/wiki/Community-Extensions

**Comment by lukasoppermann** [comment]
Perfect, thanks.
