### ISSUE TITLE
Consider using `S` modifier for regex matching

### ISSUE THREAD

**Issue by josegonzalez** [thephpleague/commonmark#71]
From the docs:

> When a pattern is going to be used several times, it is worth spending more time analyzing it in order to speed up the time taken for matching. If this modifier is set, then this extra analysis is performed. At present, studying a pattern is useful only for non-anchored patterns that do not have a single fixed starting character.

See [here](http://php.net/manual/en/reference.pcre.pattern.modifiers.php) for more details. From anecdotal experience, I was able to bring our sample listingfeed api - gets tickets from external sources, parses them, groups them - from 2 seconds to 0.5 seconds, in large part because of this modifier.

**Comment by colinodell** [comment]
Good idea!  I'll try adding this to some of the regexes and see how they affect the benchmark.

**Comment by colinodell** [comment]
I've tried using this modifier in virtually every regex but unfortunately I'm not seeing any performance gains - the benchmarks are showing roughly the same results with or without the `S` modifier.

I think the reason for this is two-fold:

1. Most of the regexes are anchored, and the docs state that studying anchored patterns isn't particularly useful:  `At present, studying a pattern is useful only for non-anchored patterns that do not have a single fixed starting character.`

2. Calls to `preg_` functions only account for 3.66% of execution time.  Assuming we could double the performance of these calls, those affects wouldn't be very noticeable (within the margin of error).

So for those reasons I'm going to close this issue, but I will definitely keep this modifier in mind should we ever add new regexes in the future which could benefit from it.  Thanks for the info!   :)

**Comment by josegonzalez** [comment]
Interesting, good call on benchmarking!
