### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms

### ISSUE THREAD

**Issue by colinodell** [thephpleague/commonmark#724]
GitHub has recently rolled out a [public beta for their issue forms feature](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). This would allow you to create interactive issue templates and validate them :exploding_head:.

We currently use the [older issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use our [existing issue templates](https://github.com/thephpleague/commonmark/tree/main/.github/ISSUE_TEMPLATE) as a reference for this PR.

(GitHub also has a [short guide](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#converting-a-markdown-issue-template-to-a-yaml-issue-form-template) showing an example of what the upgrade process looks like)

Tasks summary:

- [ ]  Fork & clone this repository
- [ ]  Replace `.github/ISSUE_TEMPLATE/1_Conversion_error.md` with a new issue form with `.yaml` extension
- [ ]  Replace `.github/ISSUE_TEMPLATE/2_Bug_report.md` with a new issue form  with `.yaml` extension
- [ ]  Replace `.github/ISSUE_TEMPLATE/3_Feature_request.md` with a new issue form  with `.yaml` extension
- [ ]  Keep `.github/ISSUE_TEMPLATE/4_Question.md` as-is, since we don't want people creating issues from that
- [ ]  Push changes to `main` and test issue forms on your fork
- [ ]  Submit pull request

Are you ready to work on this issue? :thinking: Let us know, and we will assign it to you :blush: 

**Happy Hacktoberfest!**

**Comment by sudiptog81** [comment]
Can work on this :eyes:

**Comment by colinodell** [comment]
Thanks! It's all yours :)
