### ISSUE TITLE
Question: ordered lists starting with 0

### ISSUE THREAD

**Issue by mici-** [thephpleague/commonmark#74]
If I'm not mistaken, ordered lists starting with any positive number will have the start='N' attribute, but this is not the case when starting a list with 0, it will simply start it at the default 1.

Is this expected behavior based on the spec (I did not see any rules prohibiting it, but I could be wrong), and would you consider adding it as a feature? I think it would be beneficial seeing how especially in areas related to computing often indexes begin with a 0.

**Comment by colinodell** [comment]
That's a great question - let me look into this and get back to you.

**Comment by colinodell** [comment]
I've re-read the spec and came to the same conclusion as you - `0.` is definitely a valid ordered list marker, so the `start` attribute should be set to `0`.  I'll work on implementing a fix for this.

I've also filed an issue "upstream" with the JS implementation that we're based off: jgm/commonmark.js#10

Thanks for letting us know about this!

**Comment by colinodell** [comment]
This has been fixed.  Thanks!

**Comment by mici-** [comment]
Thank you for the quick fix!
