### ISSUE TITLE
<figure> and <figcaption> for images

### ISSUE THREAD

**Issue by ohreally** [thephpleague/commonmark#757]
### Description

I would love to be able to configure CommonMark to display `<figure>` and `<figcaption>` tags around images. This would facilitate styling using CSS.

Related documentation at [whatwg.org](https://html.spec.whatwg.org/multipage/):
- [The `figure` element](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element)
- [The `figcaption` element](https://html.spec.whatwg.org/multipage/grouping-content.html#the-figcaption-element)

### Example

This markdown

```
![Captions for images are cool. Change my mind.](/memes/captions.jpg)
```

currently converts to

```
<img src="/memes/captions.jpg" alt="Captions for images are cool. Change my mind." />
```

I would like to be able to set the '_image\_as\_figure_' configuration option, to instead have it converted to

```
<figure>
<img src="/memes/captions.jpg" alt="Captions for images are cool. Change my mind." />
<figcaption>Captions for images are cool. Change my mind.</figcaption>
</figure>
```

It would be even better if I could also set the '_figcaption\_position_' configuration option to '_top_' or '_bottom_' to have the `<figcaption>` inserted above or below the `<img>` tag. The rest of the styling would then be done using CSS (including `display:none` if necessary).

### Did this project help you today? Did it make you happy in any way?

Edit: forgot to say something nice.

Yes, I'm still happy. :)

**Comment by colinodell** [comment]
Thanks for the suggestion! At this time, I don't have any plans to add this support directly to the library, but it should be very easy for you to implement this yourself :)

Basically, you'll want to create your own [custom renderer](https://commonmark.thephpleague.com/2.0/customization/rendering/)  that generates your desired HTML.  Here's a quick example I threw together (but haven't tested) that decorates the built-in `ImageRenderer`:

```php
use League\CommonMark\Extension\CommonMark\Node\Inline\Image;
use League\CommonMark\Node\Node;
use League\CommonMark\Renderer\ChildNodeRendererInterface;
use League\CommonMark\Renderer\NodeRendererInterface;
use League\Config\ConfigurationAwareInterface;
use League\Config\ConfigurationInterface;

final class ImageAsFigureRenderer implements NodeRendererInterface, ConfigurationAwareInterface
{
    private ImageRenderer $imageRenderer;

    /** @psalm-readonly-allow-private-mutation */
    private ConfigurationInterface $config;

    public function __construct(ImageRenderer $imageRenderer)
    {
        $this->imageRenderer = $imageRenderer;
    }

    /**
     * @param Image $node
     *
     * {@inheritDoc}
     *
     * @psalm-suppress MoreSpecificImplementedParamType
     */
    public function render(Node $node, ChildNodeRendererInterface $childRenderer): \Stringable
    {
        Image::assertInstanceOf($node);

        $imageHtml   = $this->imageRenderer->render($node, $childRenderer);
        $captionHtml = $childRenderer->renderNodes($node->children());
        
        return \sprintf('<figure>%s<figcaption>%s</figcaption></figure>', $imageHtml, $captionHtml);
    }

    public function setConfiguration(ConfigurationInterface $configuration): void
    {
        $this->config = $configuration;
    }
}
```

And then you'd [instantiate/register it](https://commonmark.thephpleague.com/2.0/customization/rendering/#designating-renderers) like this:

```php
$environment = new Environment();
$environment->addRenderer(Image::class, new ImageAsFigureRenderer(new ImageRenderer()));
```

Again, that's all untested but it should get you at least 90% of the way there!

**Comment by ohreally** [comment]
That does look very easy...

I'll play around with that. Thanks!
