### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by yochanan-gurovich** [thephpleague/commonmark#759]
### Version(s) affected

2.0.2

### Description

Deprecated: Return type of League\CommonMark\Util\ArrayCollection::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ../vendor/league/commonmark/src/Util/ArrayCollection.php on line 110

### How to reproduce
Install php 8.1, version 2.0.2 of this package and convert this to HTML:
<pre>
```
code inside 
```
</pre>

**Comment by colinodell** [comment]
Fixed via #762
