### ISSUE TITLE
Russian in markdown

### ISSUE THREAD

**Issue by mikield** [thephpleague/commonmark#78]
Russian text with `<code>` renders like: 
<li>Из: твоя <code>оя featu</code> ветка</li>

But must render like:

<li>Из: твоя <code>feature</code> ветка </li>

It repeats some symbols.

When in line are only english sybmols - is OK

**Comment by colinodell** [comment]
Thanks for reporting this bug!  We'll take a look at this.

Would you be able to post the exact Markdown that causes this issue?  I could probably figure it out myself, but if you have it handy that makes my life a bit easier :) Simply indent it with 4 spaces like this:

    See how `GitHub` doesn't try parsing <code>this</code> as **Markdown**?

**Comment by colinodell** [comment]
The `Cursor` class wasn't properly calculating string positions with Russian characters (or any multi-byte characters for that matter).  I've implemented a solution which resolves the issue.  I was also able to identify a couple other troublesome areas - these have also been corrected.

These fixes will be part of the 0.7.1 release coming soon :)

Thanks again for reporting this issue!
