### ISSUE TITLE
support symfony/finder:^6.0.0

### ISSUE THREAD

**Issue by chenghung** [thephpleague/commonmark#834]
### Description

we are unable to upgrade to laravel 9 due to commonmark depends on finder:^5.3

### Example

symfony/finder: "^5.3|^6.0"

**Comment by colinodell** [comment]
Hmm... `symfony/finder` is a dev dependency and shouldn't be affecting anyone using this library (except for maintainers working within this repository).

Would you mind running `composer why-not symfony/finder ^6.0` and sharing the output here?
