### ISSUE TITLE
HTML `style` tags are partially escaped

### ISSUE THREAD

**Issue by pReya** [thephpleague/commonmark#840]
### Version(s) affected

2.0.2

### Description

Hey, I'm using CommonMark, which is included in Laravel 8.65. Not sure how to look up the exact version number (sorry, my experience with Composer is limited).

When I use the `GithubFlavoredMarkdownConverter` with the `html_input` option set to default/allow, then I do receive partially escaped brackets in an included `<style>` tag.

Has this been fixed in any of the later releases already?

### How to reproduce

Using this code snippet:

```php
$converter = new GithubFlavoredMarkdownConverter(["html_input" => "allow"]);
$output = $converter->convertToHtml("<style>.class{color: red;}</style>\n# LOL Test");
dd($output);
```

Expected output would be:
```
<style>.class{color: red;}</style>
<h1>LOL Test</h1>
```

Actual output:
```
&lt;style>.class{color: red;}&lt;/style>
<h1>LOL Test</h1>
```

**Comment by colinodell** [comment]
Hey there! This behavior is required by [the GitHub Flavored Markdown specification](https://github.github.com/gfm/#disallowed-raw-html-extension-).  This escaping will always occur for those specific HTML tags regardless of what the `html_input` option is set to.

If you want the rest of the GFM features without this behavior, you'll need to [manually add](https://commonmark.thephpleague.com/2.2/extensions/overview/#usage) only the [relevant extensions](https://github.com/thephpleague/commonmark/blob/2.2/src/Extension/GithubFlavoredMarkdownExtension.php#L27-L31) (except for `DisallowedRawHtmlExtension`) which should give the behavior you're looking for.

> Not sure how to look up the exact version number (sorry, my experience with Composer is limited).

No worries! You can get that information in the future by running `composer show` or `composer show league/commonmark` :)

**Comment by colinodell** [comment]
Alternatively, there is a configuration option you can set to tell that extension to not disallow `<style>` - see https://commonmark.thephpleague.com/2.2/extensions/disallowed-raw-html/ for details and an example.

**Comment by pReya** [comment]
Thank you very much @colinodell. I was not aware, that this is part of the GFM specification. It looked like a bug to me due to the partial escaping. Thanks for the input on how to ship around this problem. I will use one of the mentioned methods.
