### ISSUE TITLE
Migration guide misses the removal of addBlockRenderer

### ISSUE THREAD

**Issue by lyrixx** [thephpleague/commonmark#901]
Hello,

I was reading https://commonmark.thephpleague.com/2.0/upgrading/consumers/#commonmarkconverter-and-githubflavoredmarkdownconverter-constructors

And I switched to 2.x but I got an error:
```
  Invalid service "League\CommonMark\Environment\Environment": method "addBlockRenderer()" does not exist.  
```

We use a custom rendered, but the migration guide does not explain how to migrate this code.

**Comment by lyrixx** [comment]
It's in the [CHANGELOG](https://github.com/thephpleague/commonmark/blob/2.3/CHANGELOG.md)

Sorry for the noise.

(And thanks for your work on this project)

**Comment by colinodell** [comment]
No problem! And yeah, I split the upgrade guide into three different versions. The one for developers creating custom parsers and renderers covers that change here: https://commonmark.thephpleague.com/2.0/upgrading/developers/#rendering-changes  But of course anyone who is using (but didn't create) a custom renderer probably wouldn't look at that page, so if you wanted to open a PR to add it on the "consumers" version of the upgrade guide, feel free!
