### ISSUE TITLE
`HtmlElement::__toString()` generates non-compatible HTML

### ISSUE THREAD

**Issue by WinterSilence** [thephpleague/commonmark#916]
### Version(s) affected

2.3.5

### Description

`HtmlElement::__toString()` mix HTML5 and HTML4:
- '/' character before '>' is redundant for HTML5 void elements
- HTML4 not support empty attribute syntax

To generate code valid in HTML4 and HTML5, need use "double-quoted value" syntax instead "empty attribute" syntax for output boolean attributes.

### How to reproduce

-

**Comment by colinodell** [comment]
Thanks for reaching out!

This library does not support HTML4, as [that spec was retired in 2018](https://www.w3.org/standards/history/html401).  We instead aim to support [the HTML Living Standard](https://html.spec.whatwg.org/multipage/) (the successor to HTML5), [which does allow slashes in void elements](https://html.spec.whatwg.org/multipage/syntax.html#start-tags):

> Then, **if the element is one of the void elements**, or if the element is a foreign element, then **there may be a single U+002F SOLIDUS character (/). This character has no effect on void elements**, but on foreign elements it marks the start tag as self-closing.

(emphasis added)

While the slashes are not necessary, they are valid.  The CommonMark spec also uses these in its example which we test against, so we'll continue to use them here.

**Comment by WinterSilence** [comment]
@colinodell I wrote "redundant"(MAY BE), not "wrong/invalid"(SHOULD/MUST BE). No ideas why slash omit only for `input` tag.

> This library does not support HTML4

What's about XHTML5?
