### ISSUE TITLE
Allow simplified input for attribute values

### ISSUE THREAD

**Issue by MrSpoocy** [thephpleague/commonmark#943]
### Description

Related to the https://commonmark.thephpleague.com/2.3/extensions/attributes/ extension, I would like to make an adjustment. In order to make it easier for the users, I would be a bit more generous when entering values for atttributes (can be activated via configuration).

For all key-value values, where the value only consists of the following characters `A-Za-z0-9-_.` the user does not need to write quotation marks (they are set in the HTML anyway).

It is only an improvement for the operability. What is your opinion?
I would make this adjustment as part of the change in #942.

### Example

`[Goolge can help you](https://www.google.de){target=_blank}` -> `<a href="https://www.google.de" target="_blank">Goolge can help you</a>`

`### Headline {class=big}` -> `<h3 class="big">Headline</h3>`

`Total crazy{class=cms.highlight}` -> `<p class="cms.highlight">Total crazy</p>`

**Comment by colinodell** [comment]
Looking at [one of our test cases](https://raw.githubusercontent.com/thephpleague/commonmark/2.3/tests/functional/Extension/Attributes/data/table_attributes.md) it seems like this might already be supported:

https://github.com/thephpleague/commonmark/blob/32891d1aa3a7ad4cad6a60177d3b4bb8dbdff96b/tests/functional/Extension/Attributes/data/table_attributes.md?plain=1#L1-L4

  Would you be open to adding [some more test cases](https://github.com/thephpleague/commonmark/blob/32891d1aa3a7ad4cad6a60177d3b4bb8dbdff96b/tests/unit/Extension/Attributes/Util/AttributesHelperTest.php#L40) to confirm whether this works as expected?  We can then commit those new test cases if they pass or explore options (like your proposal) if they don't currently work.

**Comment by MrSpoocy** [comment]
Then maybe it's a bug I found. I will extend the tests tomorrow morning. What I can already say, with me the following did not go (the point at the end provides for problems):

```
This is
a test [Google](https://www.google.de){target=_blank}.

Second line
```
