### ISSUE TITLE
 "League\Config\ConfigurationProviderInterface" not found

### ISSUE THREAD

**Issue by nenge123** [thephpleague/commonmark#954]
### Version(s) affected

2.3

### Description

PHP Fatal error:  During inheritance of League\CommonMark\CommonMarkConverter, while autoloading League\CommonMark\Environment\Environment: Uncaught Error: Interface "League\Config\ConfigurationProviderInterface" not found in D:\WEB\wwwroot\xiunobbs4\plugin\document\class\League\CommonMark\Environment\EnvironmentInterface.php:26

### How to reproduce

```
        if(empty($this->converter)){
            $this->converter = new CommonMarkConverter();
        }
        return $this->converter;
```

**Comment by colinodell** [comment]
Are you using Composer to install this library?  If so, double-check that you've required the `vendor/autoload.php` file, and try running `composer dump-autoload`.

**Comment by nenge123** [comment]
> Are you using Composer to install this library?  If so, double-check that you've required the `vendor/autoload.php` file, and try running `composer dump-autoload`.

but i can't run "composer install",
why release not a offline version.
