### ISSUE TITLE
LaTeX output

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/commonmark#97]
I am in a bit of a predicament and I believe I can code my way out of it. 

Currently I am trying to get my API book done as print, but LeanPub's PDF generation is... too simple. It has a lot of bugs and problems and I can't fix them, so I am trying to find a solution I can work with.

[Markua](http://markua.com/), LeanPub's Markdown flavor, is a CommonMark superset. A potential [league/markua](https://github.com/dshafik/markua) package was started by @dshafik a while ago.

Luckily league/commonmark already outputs to an AST, so all we really need to do is output from that AST to LaTeX. At that point the LaTeX can be smashed through pandoc and I have a bazillion output formats to work with.

I have been talking to @cebe about this, and he already has [some code](https://github.com/cebe/markdown-latex) which is doing kinda that with his own markdown package.

@colinodell how tough do you think it would be, to get some `convertToLatex()` functionality all up in here, alongside the HTML output we already have.

Would it be best as another library, or baked into this, and would it support Markua stuff (and any other added flavor) nicely?

**Comment by colinodell** [comment]
I really like the idea of creating LaTeX documents with CommonMark, and it's definitely possible to do.  My biggest question is how to best separate things.

Right now we have a [CommonMarkCoreExtension](https://github.com/thephpleague/commonmark/blob/master/src/Extension/CommonMarkCoreExtension.php) which declares which parsers, processors, and renderers are required to convert CommonMark into HTML.  The parsers and processes are used to create the AST which the renderers convert to HTML.

I'm thinking we'll probably want to break this Extension in two - one Extension class to define the parsing stuff and another to define which renderers to use.  That should make it much easier to swap out the HTML rendering for LaTeX.

Following this line of thinking, I'm wondering if we shouldn't also break the current project into three packages:

 - `league/commonmark-core` - The core parsing stuff; takes CommonMark input and produces the AST
 - `league/commonmark-html` - Converts the AST into HTML
 - `league/commonmark` - `requires` both packages above and adds the `CommonMarkConverter` convenience wrapper

We could then have "official" extensions (much like Omnipay):

 - `league/commonmark-latex`
 - `league/markua` or `league/commonmark-markua`

What are your thoughts on that?  Would this be a beneficial separation or I am taking things to far?

**Comment by cebe** [comment]
Wow, thanks for your time to work this out! I have not looked at the code yet so I am not sure we need this separation. There is just another important point to add here:

Markdown as defined by John Gruber and also by CommonMark is designed to live together with HTML so it defines a lot of stuff on how to parse HTML blocks inside of Markdown and also Markdown inside of HTML.
This coupling is a bit of a burden when it comes to converting Markdown to other markup such as LaTeX. There is no simple way of converting HTML to LaTeX and I do not think that this should be part of the parser. Moreover the thing that converts Markdown to LaTeX should be able to understand LaTeX to some extend to be able to write plain LaTeX inside of the Markdown as it is possible with HTML.

So to conclude: the thing created here will not strictly follow the CommonMark spec because it drops out the HTML part and possibly plugs in LaTeX there.

**Comment by philsturgeon** [comment]
> Markdown ... is designed to live together with HTML 

Agreed there. I think league/commonmark as it is should continue to handle HTML output via the AST, but the LaTeX parser should be an API for taking that AST and doing something useful with it.

My end goal is to make a CLI which will let people take their LeanPub Markua book and export it as something useful, potentially getting them away from the dependency on LeanPub for everything. 

By wrapping commonmark + markua + pandoc and having commonmark-latex as the glue (the missing piece of the puzzle) I could make a very nice config based system that would do a lot of the work.

Either that approach, or use it as a one-off export from Markua to LaTeX so direct editing becomes an option. One of the two..

Anyhow, LaTeX probably shouldn't go into the main package, but HTML could stay.

**Comment by colinodell** [comment]
I agree, I don't want to put LaTeX in this package.

I'd still be open to [breaking this project into multiple packages](https://github.com/thephpleague/commonmark/issues/97#issuecomment-103161297) should the need arise, but it doesn't seem necessary now.  I'm therefore going to close this issue but feel free to re-open it if needed :)

**Comment by cebe** [comment]
I have created a repostitory: https://github.com/cebe/commonmark-latex whoever wants to help implementing this, feel free to create issues and pull requests there, I can also add you as contributors for direct push access. I will most likely will give it a try in a month or two if noone has started earlier.

**Comment by colinodell** [comment]
Nice!  I will definitely be keeping an eye on that.

**Comment by samwilson** [comment]
I've had a go at implementing (some of) a LaTeX renderer: https://github.com/samwilson/commonmark-latex

Still to come (amongst other things) is a way to handle downloading of images (where they're not local), and footnotes.
