### ISSUE TITLE
Smartypants

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/commonmark#98]
This is probably another package, but in the same vein as the potential markua package, it would be good to get [Smartypants](http://daringfireball.net/projects/smartypants/) involved.

This would help CommonMark projects be usable for printed books and whatnot, turning standard quotes into curly quotes and other similar bits.

**Comment by philsturgeon** [comment]
Although if https://github.com/thephpleague/commonmark/issues/97 happens I don't know if LaTeX/Pandoc will handle that stuff magically. Either way, would be a nice one.

**Comment by cebe** [comment]
for LaTeX these should be converted not to the unicode characters but LaTeX specific syntax: http://en.wikipedia.org/wiki/Quotation_mark#Typewriters_and_early_computers

**Comment by philsturgeon** [comment]
Cool. Priority goes down the list, meaning I won’t bother to do it. :D

-- 
Phil

**Comment by cebe** [comment]
you need this more than me right now, so we'll see ;)

**Comment by philsturgeon** [comment]
I actually don’t need it at all if LaTeX does that stuff. Just a feature suggestion now.

**Comment by cebe** [comment]
not sure how this works in english, but for german quotes you need special sytnax in LaTeX. Will check it out.

**Comment by philsturgeon** [comment]
Oh I see, so I _will_ need it. I just need to make sure it outputs to either HTML entities or LaTeX special syntax.

-- 
Phil

**Comment by cebe** [comment]
exactly

**Comment by cebe** [comment]
german wikipedia has more details about the characters to be used: http://de.wikipedia.org/wiki/Anf%C3%BChrungszeichen#Kodierung

**Comment by colinodell** [comment]
Smartypants is a great idea, but I do think it should be its own separate package.  You might be able to implement it as an Inline Processor (which iterates over Inlines, performing modifications to them).  If not then we could look at expanding the "Extension API" to make these types of addons easier to implement.

**Comment by cebe** [comment]
One important part is that it should not be applied to code blocks and also inline code. Will check out the API and let you know if there are limitations.
