### ISSUE TITLE
Algolia Search Not Giving Any Results

### ISSUE THREAD

**Issue by mahi-pas** [thephpleague/commonmark#991]
### Version(s) affected

2.4

### Description

In the documentation, the search bar yields no results. In previous versions it does.
![image](https://github.com/thephpleague/commonmark/assets/47994802/f1378bc8-2ed6-4842-b52d-7774bb35a922)

### How to reproduce

Go to the website and try to search for something.

**Comment by colinodell** [comment]
Fixed via 68f7fdbc915694cfd53e27f51b0fdf22a71dde38.  Thanks for reporting this!
